=== bluevlad/Java/HKMCA_2008/WebContent/WEB-INF/reports/excelUpload/excel-upload.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
	 mvc conrol Configuration
	 Version : 1.0	(2005.03.30)
	 Author : Kim Sang Joon
-->
<!-- 
	configuration is the root element. 
-->
<!ELEMENT upload  (sqls|fields|samplesql)*>
<!ATTLIST upload
	desc CDATA  #IMPLIED 
	startrow CDATA "0"
>
<!ELEMENT sqls ((sql)+)>
<!ELEMENT sql (#PCDATA)>
<!ATTLIST sql 
	seq 	CDATA  #REQUIRED 
>

<!ELEMENT fields ((field)*)>
<!ELEMENT field EMPTY>
<!--
	check 가 true인 필드가 null 이면 import stop
-->
<!ATTLIST field col 	CDATA  #REQUIRED >
<!ATTLIST field fieldname CDATA  #REQUIRED  >
<!ATTLIST field title CDATA  #IMPLIED  >
<!ATTLIST field type (string|number|integer) "string"  >
<!ATTLIST field check (true|false) "true"  >
<!ATTLIST field sample CDATA  #IMPLIED >
<!ATTLIST field desc CDATA  #IMPLIED >
<!ELEMENT samplesql (#PCDATA)>

=== bluevlad/Java/MAF_JDK1.5/WebContent/WEB-INF/reports/excelUpload/upload_lecreq.xml
<?xml version="1.0" encoding="UTF-8"  ?>
<!DOCTYPE maf-command PUBLIC
         "-//Miranet//DTD maf-command config XML V1.0//EN"
         "excel-upload.dtd">
<upload desc="upload 수강신청 등록" startrow="1">
	<sqls>
		<sql seq="0">
			{call SP_WCC_LEC_REQ_BATCH_INSERT(:userid, :leccode, :lecnumb, :reqstat, :is_pay, :update_id)}
		</sql>
	</sqls>
	<fields>
		<field col="0" fieldname="userid" title="User ID" sample="dipin2002" desc="User ID" />
		<field col="1" fieldname="leccode" title="Lecture Code" sample="WOO-226-R-200706" desc="Lecture Code" />
		<field col="2" fieldname="lecnumb" title="Lecture Num" sample="1" desc="Lecture Num" />
		<field col="3" fieldname="reqstat" title="Status" sample="LR" desc="Status" />
		<field col="4" fieldname="req_dt" title="Request Date" sample="" desc="Request Date" />
		<field col="5" fieldname="lecname" title="Lecture Name" sample="" desc="Lecture Name" />
		<field col="6" fieldname="alias_cd" title="Local Code" sample="" desc="Local Code" />
		<field col="7" fieldname="nm" title="User Name" sample="" desc="User Name" />
	</fields>
</upload>

=== bluevlad/Java/HKMCA_2008/WebContent/WEB-INF/reports/excelUpload/etest_bank.xml
<?xml version="1.0" encoding="UTF-8"  ?>
<!DOCTYPE maf-command PUBLIC
         "-//Miranet//DTD maf-command config XML V1.0//EN"
         "excel-upload.dtd">
<upload desc="eTest 문제은행 등록" startrow="1">
	<sqls>
		<sql seq="0">
		 INSERT INTO exm_bnk (queid,
             qweowner, quetitle, quetext, queviw1, queviw2, queviw3,
             queviw4, queviw5, queviw6, queviw7, queviw8, queviw9, queviw10, 
             queviw11, queviw12, queviw13, queviw14, queviw15, queviw16, queviw17, 
             queviw18, queviw19, queviw20, quecount,
             quedesc, queansw, quescore, quetype, quelevel,  cat_id,
             reg_usn, update_usn,ACTIVE_YN
            )
     VALUES (to_char(sysdate,'DD') || lpad( seq_exm_bnk_id.NEXTVAL,10,0), 
     		 :qweowner, :quetitle, :quetext, :queviw1, :queviw2, :queviw3,
             :queviw4, :queviw5, :queviw6, :queviw7, :queviw8, :queviw9, :queviw10, 
             :queviw11, :queviw12, :queviw13, :queviw14, :queviw15, :queviw16, :queviw17, 
             :queviw18, :queviw19, :queviw20, :quecount,
             :quedesc, :queansw, :quescore, :quetype, :quelevel,  :cat_id,
             :reg_usn, :reg_usn,'Y'
            )
		</sql>
	</sqls>
	<fields>
		<field col="0" fieldname="cat_id" title="cat_id" type="string" check="true" sample="101" desc="Category ID" />
		<field col="1" fieldname="quetitle" title="quetitle" type="string" check="true" sample="What happens to the voltage output of the map sensor during acceleration?" desc="Queue Title" />
		<field col="2" fieldname="quetext" title="quetext" type="string" check="true" sample="" desc="View" />
		
		<field col="3" fieldname="quecount" title="quecount" type="string" check="true" sample="4" desc="Queue COunt" />
		<field col="4" fieldname="queansw" title="queansw" type="string" check="true" sample="2#3" desc="Answer" />
		<field col="5" fieldname="quescore" title="quescore" type="string" check="true" sample="1" desc="Score" />
		<field col="6" fieldname="quetype" title="quetype" type="string" check="true" sample="s" desc="Type[s:Single choice, m:Mulitple choice, t:Short answer, s:Essay type]" />
		<field col="7" fieldname="quelevel" title="quelevel" type="string" check="true" sample="3" desc="Difficult[5:Very Difficult 4:Difficult 3:Normal 2:Easy 1 : Very Easy]" />
		
		<field col="8" fieldname="queviw1" title="queviw1" type="string" sample="Decreased" desc="View 1" />
		<field col="9" fieldname="queviw2" title="queviw2" type="string" sample="Increased" desc="View 2" />
		<field col="10" fieldname="queviw3" title="queviw3" type="string" sample="No change" desc="View 3" />
		<field col="11" fieldname="queviw4" title="queviw4" type="string" sample="Close to 0V" desc="View 4" />
		<field col="12" fieldname="queviw5" title="queviw5" type="string" sample="" desc="View 5" />
		<field col="13" fieldname="queviw6" title="queviw6" type="string" sample="" desc="View 6" />
		<field col="14" fieldname="queviw7" title="queviw7" type="string" sample="" desc="View 7" />
		<field col="15" fieldname="queviw8" title="queviw8" type="string" sample="" desc="View 8" />
		<field col="16" fieldname="queviw9" title="queviw9" type="string" sample="" desc="View 9" />
		<field col="17" fieldname="queviw10" title="queviw10" type="string" sample="" desc="View 10" />
		<field col="18" fieldname="queviw11" title="queviw11" type="string" sample="" desc="View 11" />
		<field col="19" fieldname="queviw12" title="queviw12" type="string" sample="" desc="View 12" />
		<field col="20" fieldname="queviw13" title="queviw13" type="string" sample="" desc="View 13" />
		<field col="21" fieldname="queviw14" title="queviw14" type="string" sample="" desc="View 14" />
		<field col="22" fieldname="queviw15" title="queviw15" type="string" sample="" desc="View 15" />
		<field col="23" fieldname="queviw16" title="queviw16" type="string" sample="" desc="View 16" />
		<field col="24" fieldname="queviw17" title="queviw17" type="string" sample="" desc="View 17" />
		<field col="25" fieldname="queviw18" title="queviw18" type="string" sample="" desc="View 18" />
		<field col="26" fieldname="queviw19" title="queviw19" type="string" sample="" desc="View 19" />
		<field col="27" fieldname="queviw20" title="queviw20" type="string" sample="" desc="View 20" />

		<field col="28" fieldname="quedesc" title="quedesc" type="string"  check="true" sample="" desc="Description" />
	</fields>
</upload>

=== bluevlad/Java/MAF_JDK1.5/WebContent/WEB-INF/reports/excelUpload/etest_trans.xml
<?xml version="1.0" encoding="UTF-8"  ?>
<!DOCTYPE maf-command PUBLIC
         "-//Miranet//DTD maf-command config XML V1.0//EN"
         "excel-upload.dtd">
<upload desc="eTest 문제은행 등록" startrow="1">
	<sqls>
		<sql seq="0">
		MERGE INTO exm_bnk_lang dst
     USING (SELECT :queid queid, :lang lang, :quetitle quetitle, :quetext quetext, :queviw1 queviw1,
                   :queviw2 queviw2, :queviw3 queviw3, :queviw4 queviw4, :queviw5 queviw5,
                   :queviw6 queviw6, :queviw7 queviw7, :queviw8 queviw8, :queviw9 queviw9,
                   :queviw10 queviw10, :queviw11 queviw11, :queviw12 queviw12, :queviw13 queviw13,
                   :queviw14 queviw14, :queviw15 queviw15, :queviw16 queviw16, :queviw17 queviw17,
                   :queviw18 queviw18, :queviw19 queviw19, :queviw20 queviw20,
                   :quedesc quedesc, :queansw queansw, :active_yn active_yn,
                   :update_usn update_usn
              FROM DUAL) src
        ON (    dst.queid = src.queid
            AND dst.lang = src.lang)
   WHEN MATCHED THEN
      UPDATE
         SET quetitle = src.quetitle, quetext = src.quetext, 
             queviw1 = src.queviw1, queviw2 = src.queviw2, queviw3 = src.queviw3,
             queviw4 = src.queviw4, queviw5 = src.queviw5, queviw6 = src.queviw6,
             queviw7 = src.queviw7, queviw8 = src.queviw8, queviw9 = src.queviw9,
             queviw10 = src.queviw10, queviw11 = src.queviw11, queviw12 = src.queviw12, 
             queviw13 = src.queviw13, queviw14 = src.queviw14, queviw15 = src.queviw15, 
             queviw16 = src.queviw16, queviw17 = src.queviw17, queviw18 = src.queviw18, 
             queviw19 = src.queviw19, queviw20 = src.queviw20, 
             quedesc = src.quedesc, queansw = src.queansw,
             active_yn = src.active_yn, update_dt = SYSDATE, update_usn = src.update_usn
   WHEN NOT MATCHED THEN
      INSERT (queid, lang, quetitle, quetext, queviw1, queviw2, queviw3, queviw4, queviw5, queviw6,
              queviw7, queviw8, queviw9, queviw10, queviw11, queviw12, queviw13, queviw14, queviw15,
              queviw16, queviw17, queviw18, queviw19, queviw20, quedesc, queansw, active_yn, reg_usn, reg_dt,
              update_dt, update_usn)
      VALUES (src.queid, src.lang, src.quetitle, src.quetext, src.queviw1, src.queviw2, src.queviw3,
              src.queviw4, src.queviw5, src.queviw6, src.queviw7, src.queviw8, src.queviw9,
              src.queviw10, src.queviw11, src.queviw12, src.queviw13, src.queviw14, src.queviw15, 
              src.queviw16, src.queviw17, src.queviw18, src.queviw19, src.queviw20, 
              src.quedesc, src.queansw, src.active_yn, src.update_usn, SYSDATE,
              SYSDATE, src.update_usn)
		</sql>
	</sqls>
	<fields>
		<field col="0" fieldname="queid" title="queid" type="string" />
		<field col="1" fieldname="lang" title="lang" type="string" />
		<field col="2" fieldname="active_yn" title="active_yn" type="string" />
		<field col="3" fieldname="quetitle" title="quetitle" type="string" />
		<field col="4" fieldname="quetext" title="quetext" type="string" />
		<field col="5" fieldname="queansw" title="queansw" type="string" />
		<field col="6" fieldname="queviw1" title="queviw1" type="string" />
		<field col="7" fieldname="queviw2" title="queviw2" type="string" />
		<field col="8" fieldname="queviw3" title="queviw3" type="string" />
		<field col="9" fieldname="queviw4" title="queviw4" type="string" />
		<field col="10" fieldname="queviw5" title="queviw5" type="string" />
		<field col="11" fieldname="queviw6" title="queviw6" type="string" />
		<field col="12" fieldname="queviw7" title="queviw7" type="string" />
		<field col="13" fieldname="queviw8" title="queviw8" type="string" />
		<field col="14" fieldname="queviw9" title="queviw9" type="string" />
		<field col="15" fieldname="queviw10" title="queviw10" type="string" />
		<field col="16" fieldname="queviw11" title="queviw11" type="string" />
		<field col="17" fieldname="queviw12" title="queviw12" type="string" />
		<field col="18" fieldname="queviw13" title="queviw13" type="string" />
		<field col="19" fieldname="queviw14" title="queviw14" type="string" />
		<field col="20" fieldname="queviw15" title="queviw15" type="string" />
		<field col="21" fieldname="queviw16" title="queviw16" type="string" />
		<field col="22" fieldname="queviw17" title="queviw17" type="string" />
		<field col="23" fieldname="queviw18" title="queviw18" type="string" />
		<field col="24" fieldname="queviw19" title="queviw19" type="string" />
		<field col="25" fieldname="queviw20" title="queviw20" type="string" />
		<field col="26" fieldname="quedesc" title="quedesc" type="string" />
	</fields>
</upload>

=== bluevlad/Java/MAF_JDK1.5/WebContent/WEB-INF/reports/excelUpload/bas_certi.xml
<?xml version="1.0" encoding="UTF-8"  ?>
<!DOCTYPE maf-command PUBLIC
         "-//Miranet//DTD maf-command config XML V1.0//EN"
         "excel-upload.dtd">
<upload desc="upload group certification" startrow="1">
	<sqls>
		<sql seq="0">
			 INSERT INTO BAS_CERTI
			    (usn, certi_no, certi_id, certi_date, insert_dt, insert_id)
			  VALUES
			    (:usn, :certi_no, :certi_id, :certi_date, sysdate, :insert_id)
		</sql>
	</sqls>
	<fields>
		<field col="0" fieldname="usn" title="usn" check="true" sample="2049988" desc="USER ID" />
		<field col="1" fieldname="certi_no" title="certi_no" check="true" sample="SEN-0003" desc="Certi. Issue No." />
		<field col="2" fieldname="certi_id" title="certi_id" check="true" sample="SEN" desc="certificate issue code" />
		<field col="3" fieldname="certi_date" title="certi_date" sample="2007-01-01" desc="certification date" />
		<field col="4" fieldname="insert_id" title="insert_id" sample="admin" desc="User ID of Register" />
	</fields>
</upload>
