=== bluevlad/Java/MAF_JDK1.4/WebContent/WEB-INF/reports/excel/excel-viewer.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
	 mvc conrol Configuration
	 Version : 1.0	(2005.03.30)
	 Author : Kim Sang Joon
-->
<!-- 
	configuration is the root element. 
-->
<!ELEMENT viewer (field)*>
<!ATTLIST viewer
	filename CDATA #IMPLIED 
	title CDATA #IMPLIED 
	desc CDATA  #IMPLIED 
>
<!ELEMENT field EMPTY>
<!ATTLIST field id 	CDATA  #REQUIRED >
<!ATTLIST field title CDATA  #REQUIRED  >
<!ATTLIST field type (string|number) "string"  >
<!ATTLIST field align (general|left|center|right) "general" >
<!ATTLIST field format CDATA #IMPLIED  >
<!ATTLIST field style (string|money|float|date|percent) "string"  >
<!--
	style 지정시 formatNo는 무시됨 
	0 "General"
	1 "0"
-->

=== bluevlad/Java/MAF_JDK1.7/WebContent/WEB-INF/reports/excel/etest_trans_source.xml
<?xml version="1.0" encoding="UTF-8"  ?>
<!DOCTYPE maf-command PUBLIC
         "-//Miranet//DTD maf-command config XML V1.0//EN"
         "excel-viewer.dtd">
<viewer filename="etest.xls" title="">
	<field id="queid" title="queid" type="string" />
	<field id="lang" title="lang" type="string"/>
	<field id="active_yn" title="active_yn" type="string"/>
	<field id="quetitle" title="quetitle" type="string"/>
	<field id="quetext" title="quetext" type="string"/>
	<field id="queansw" title="queansw" type="string"/>
	<field id="queviw1" title="queviw1" type="string"/>
	<field id="queviw2" title="queviw2" type="string"/>
	<field id="queviw3" title="queviw3" type="string"/>
	<field id="queviw4" title="queviw4" type="string"/>
	<field id="queviw5" title="queviw5" type="string"/>
	<field id="queviw6" title="queviw6" type="string"/>
	<field id="queviw7" title="queviw7" type="string"/>
	<field id="queviw8" title="queviw8" type="string"/>
	<field id="queviw9" title="queviw9" type="string"/>
	<field id="queviw10" title="queviw10" type="string"/>
	<field id="quedesc" title="quedesc" type="string"/>
</viewer>

=== bluevlad/Java/MAF_JDK1.7/WebContent/WEB-INF/reports/excel/list_jindo.xml
<?xml version="1.0" encoding="UTF-8"  ?>
<!DOCTYPE maf-command PUBLIC
         "-//Miranet//DTD maf-command config XML V1.0//EN"
         "excel-viewer.dtd">
<viewer filename="진도현황.xls" title="진도현황">
	<field id="rownum" title="No"   />
	<field id="prtcode" title="과정코드"   />
	<field id="leccode" title="강의코드"   />
	<field id="lecname" title="강의명"   />
	<field id="lec_sdate" title="강의시작일" />
	<field id="lec_edate" title="강의종료일"  />
	<field id="usrid" title="학습자ID"/>
	<field id="usernm" title="학습자명"  />
	<field id="pin" title="주민등록번호"/>
	<field id="company_nm" title="회사명"/>
	<field id="attach_company" title="소속업체"/>
	<field id="is_insurance" title="환급여부"/>
	<field id="is_grad" title="수료여부"/>
	<field id="sum_score" title="총점"/>
	<field id="test_score" title="시험"/>
	<field id="rpt_score" title="과제"/>
	<field id="jindo_score" title="진도"/>
	<field id="tot_time" title="학습시간"/>
	<field id="email" title="Email"/>
	<field id="hp" title="핸드폰번호"/>
</viewer>

=== bluevlad/Java/MAF_JDK1.5/WebContent/WEB-INF/reports/excel/excel_lecreq.xml
<?xml version="1.0" encoding="UTF-8"  ?>
<!DOCTYPE maf-command PUBLIC
         "-//Miranet//DTD maf-command config XML V1.0//EN"
         "excel-viewer.dtd">
<viewer filename="Lecture.xls" title="">
	<field id="userid" title="User ID" align="center"/>
	<field id="leccode" title="Lecture Code" align="center"/>
	<field id="lecnumb" title="Lecnumb" align="center"/>
	<field id="req_stat" title="Status"/>
	<field id="req_dt" title="Request Date"/>
	<field id="lecname" title="Lectue Name" align="center"/>
	<field id="alias_cd" title="Local Code" align="center"/>
	<field id="nm" title="User Name" align="center"/>
</viewer>
