=== bluevlad/Java/MAF_JDK1.5/WebContent/WEB-INF/maf-action/mvc-configuration.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
	 mvc conrol Configuration
	 Version : 1.0	(2005.03.30)
	 Author : Kim Sang Joon
-->
<!-- 
	configuration is the root element. 
	template-list : 테프릿 이름과 Block(Template-Info)들 정의 
-->
<!ELEMENT configuration (template-list | global-view | action)*>
<!ELEMENT template-list (template-info)*>
<!--
   template block 정보
-->
<!ELEMENT template-info (template-map | site-template)*>
<!ATTLIST template-info
	name 	ID  #REQUIRED 
	uri 	CDATA  #REQUIRED 
	desc 	CDATA #IMPLIED 
	useSiteTemplate 	(true|false) #IMPLIED
>

<!ELEMENT template-map EMPTY>
<!ATTLIST template-map
	name 	CDATA  #REQUIRED 
	uri 	CDATA  #REQUIRED 
>

<!ELEMENT site-template EMPTY>
<!ATTLIST site-template
	site 	CDATA  #REQUIRED 
	uri 	CDATA  #REQUIRED 
>

<!ELEMENT global-view (view-info)*>
<!ELEMENT view-info EMPTY>
<!--
	type : html 일반(default)
	jpdf : JasperPDFView	
-->
<!ATTLIST view-info
	name 		CDATA  #REQUIRED 
	uri 		CDATA  #IMPLIED 
	redirect 	(true|false) #IMPLIED 
	useTemplate CDATA #IMPLIED 
	desc 	CDATA #IMPLIED 
	title 	CDATA #IMPLIED 
	type 	(html|xml|jpdf|excel|json|dummy) #IMPLIED 
>

<!ELEMENT action (aliases | action-view | cmds | forms)*>
<!ELEMENT action-view (view-info)*>
<!--
	jsppath : view단의 기본 path
	단 view의 url이 /로 시작하면 무시된다.
-->
<!ATTLIST action
	uri 	CDATA  	#REQUIRED 
	type 	CDATA  	#REQUIRED 
	desc 	CDATA 	#IMPLIED 
	title 	CDATA 	#IMPLIED 
	default CDATA 	#IMPLIED 
	param CDATA #IMPLIED 
	debug 	(true|false) #IMPLIED 
	jsppath CDATA 	#IMPLIED 
>
<!ELEMENT aliases (alias)*>
<!ELEMENT alias EMPTY>
<!ATTLIST alias
	uri 	CDATA  	#REQUIRED 
	desc 	CDATA 	#IMPLIED 
	title 	CDATA 	#IMPLIED 
	default CDATA 	#IMPLIED 
	param CDATA #IMPLIED 	
>
<!ELEMENT cmds (cmd)*>
<!ELEMENT cmd EMPTY>
<!ATTLIST cmd
	name 	CDATA  	#REQUIRED 
	method 	CDATA  	#REQUIRED 
	from 	CDATA  	#IMPLIED 
	desc 	CDATA 	#IMPLIED 
	formname	CDATA 	#IMPLIED 
	authtype	(C|R|U|D) #IMPLIED
	cmdtype	(java|jsp) #IMPLIED 
>
<!ELEMENT forms (form)*>
<!ELEMENT form (input)*>
<!ATTLIST form
	name 	CDATA  #REQUIRED 
	bundle	CDATA  #IMPLIED
>
<!ELEMENT input (constraint)*>
<!ATTLIST input
	name 	CDATA  #REQUIRED 
	message CDATA  #REQUIRED 
	bundle	CDATA  #IMPLIED
	type	(text|textarea|select|check|radio|file)  #IMPLIED
	codegroup	CDATA  #IMPLIED
	maxlength 	CDATA  #IMPLIED
	arg0	CDATA  #IMPLIED
	arg1	CDATA  #IMPLIED
	arg2	CDATA  #IMPLIED
	required (true|false) #IMPLIED 
>
<!ELEMENT constraint EMPTY>
<!ATTLIST constraint
	validatorName 	CDATA  #REQUIRED 
	value	CDATA  #IMPLIED
	arg0	CDATA  #IMPLIED
	arg1	CDATA  #IMPLIED
	arg2	CDATA  #IMPLIED
>

=== bluevlad/Java/MAF_JDK1.7/WebContent/WEB-INF/maf-action/webstat.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE maf-command PUBLIC
         "-//Miranet//DTD maf-command config XML V1.0//EN"
         "mvc-configuration.dtd">
<configuration>
	<template-list>
		<template-info name="webstat" uri="/WEB-INF/jsp/mafapp/webstat/_default.jsp"/>
	</template-list>
	<action title="접속통계" uri="webstat.do" type="miraenet.app.webstat.WebStat" default="default"
	jsppath="/WEB-INF/jsp/mafapp/webstat/">
		<action-view>
			<view-info name="default" title="기본" uri="default.jsp" useTemplate="www" />
			<view-info name="fusionxml" title="기본" uri="fusionXmlData.jsp" type="xml" />
			<view-info name="user_log_day" uri="user_log_day.jsp" />
			<view-info name="byOrgType" uri="byOrgType.jsp" useTemplate="www" />
		</action-view>
		<cmds>
			<cmd name="default" method="cmdDefault"  />
			<cmd name="login" method="cmdDefault"  />
			<cmd name="firsthit" method="cmdDefault"  />
			<cmd name="data" method="cmdData"  />
			<cmd name="user_log_day" method="user_log_day" cmdtype="jsp" />
			<cmd name="byOrgType" method="cmdByOrgType"  />
		</cmds>
	</action>

</configuration>

=== bluevlad/Java/MAF_JDK1.5/WebContent/WEB-INF/maf-action/etc.xml
<?xml version="1.0" encoding="euc-kr"?>
<!DOCTYPE maf-command PUBLIC
         "-//Miranet//DTD maf-command config XML V1.0//EN"
         "mvc-configuration.dtd">
<configuration>
	<template-list></template-list>

	<global-view></global-view>
	<action title="SiteMap" uri="SiteMap.do" type="modules.common.actions.SiteMap">
		<action-view>
			<view-info name="default" uri="/WEB-INF/jsp/sitemap/sitemap.jsp" />
		</action-view>
	</action>
	<action title="우편번호 검색" uri="Zipcode.do" type="miraenet.app.zipcode.actions.Zipcode">
		<action-view>
			<view-info name="default" uri="/WEB-INF/jsp/mafapp/zipcode/zipcode.jsp" />
		</action-view>
	</action>
</configuration>

=== bluevlad/Java/HKMCA_2008/WebContent/WEB-INF/maf-action/etest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE jmf-resource PUBLIC
         "-//UBQ//DTD jmf-command config XML V1.0//EN"
         "mvc-configuration.dtd">
<configuration>
<action uri="doTest.do" type="modules.etest.learner.DoTestAction" desc="시험응시" title="시험응시"
    jsppath="/WEB-INF/jsp/etest/dotest/" default="confirm">
	<action-view>
		<view-info name="confirm" uri="confirm.jsp" useTemplate="etest" />
		<view-info name="test" uri="test.jsp" useTemplate="etest" />
	</action-view>
	<cmds>
		<cmd name="confirm" method="cmdConfirm"  />
		<cmd name="test" method="cmdTest"  />
		<cmd name="updateAnswer" method="cmdUpdateAnswer"  />
		<cmd name="updateMark" method="cmdUpdateMark"  />
		<cmd name="finish" method="cmdFinish"  />
	</cmds>
</action>

<action uri="examlist.do" type="modules.etest.learner.ExamListAction" desc="시험목록" title="시험목록"
    jsppath="/WEB-INF/jsp/etest/examlist/" default="list">
	<action-view>
		<view-info name="list" uri="list.jsp" useTemplate="www" />
		<view-info name="view" uri="view.jsp" useTemplate="www" />
		<view-info name="result" uri="result.jsp" useTemplate="www" />
		<view-info name="resultXml" uri="resultXml.jsp" />
	</action-view>
	<cmds>
		<cmd name="tree" method="getTree" authtype="R" />
		<cmd name="treeSel" method="getTreeSel" authtype="R" />
		<cmd name="list" method="cmdList" formname="frm1" authtype="R" />
		<cmd name="view" method="cmdView" formname="frm1" authtype="R" />
		<cmd name="edit" method="cmdEdit" formname="frm1" authtype="U" />
		<cmd name="update" method="cmdUpdate" formname="frm1" from="edit" authtype="U" />
		<cmd name="insert" method="cmdInsert" formname="frm1" from="update" authtype="C" />
		<cmd name="add" method="cmdAdd" formname="frm1" from="update" authtype="C" />
		<cmd name="delete" method="cmdDelete" formname="frm1" from="delete" authtype="D" />
		<cmd name="result" method="cmdResult" authtype="R" />
		<cmd name="userHistgram" method="resultXml"  authtype="R" cmdtype="jsp"/>
	</cmds>
	<forms>
		<form name="frm1" bundle="table.exm_mst">
			<input name="exmid" message="exmid" type="text" required="true" />
			<input name="exmtitle" message="exmtitle" type="text" required="true" />
			<input name="exm_sdat" message="exm_sdat" type="text" required="true" />
			<input name="exm_edat" message="exm_edat" type="text" required="true" />
			<input name="rst_status" message="rst_status" type="text" required="true" />
			<input name="active_yn" message="active_yn" type="text" />
			<input name="reg_id" bundle="common" message="field.reg_id" type="text" />
			<input name="reg_dt" bundle="common" message="field.reg_dt" type="text" />
			<input name="upt_dt" bundle="common" message="field.upt_dt" type="text" />
			<input name="upt_id" bundle="common" message="field.upt_id" type="text" />
			<input name="active_yn" bundle="common" message="select.use" type="text" />
			<input name="org_name" bundle="table.bas_org" message="org_name" type="text" />
			<input name="user_nm" bundle="table.jmf_user" message="nm" type="text" />
			<input name="questions" message="questions" bundle="table.exm_mst" type="text" />
			<input name="lang" message="lang" bundle="common" type="text" />
			<input name="exmtime" message="exmtime" bundle="table.exm_set" type="text" />
		</form>
	</forms>
</action>
</configuration>

=== bluevlad/Java/MAF_JDK1.5/WebContent/WEB-INF/maf-action/sample.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE maf-command PUBLIC
         "-//Miranet//DTD maf-command config XML V1.0//EN"
         "mvc-configuration.dtd">
<configuration>
	<template-list>
		<template-info name="inner" uri="/WEB-INF/jsp/_sample/_style1.jsp" />
	</template-list>

	<global-view>
		<view-info name="default" uri="/WEB-INF/jsp/_sample/index.jsp"  />
	</global-view>

	<action uri="default.do" type="modules.app._sample.Sample1" 
		desc="sample" 
		title="sample title" default="list">
		<action-view>
			<view-info name="list" uri="/WEB-INF/jsp/_sample/list.jsp" useTemplate="inner" />
			<view-info name="view" uri="/WEB-INF/jsp/_sample/view.jsp" useTemplate="inner" />
			<view-info name="edit" uri="/WEB-INF/jsp/_sample/edit.jsp" useTemplate="inner" />
			<view-info name="add" uri="/WEB-INF/jsp/_sample/add.jsp" useTemplate="inner" />
		</action-view>	
		<cmds>
			<cmd name="list" method="cmdList" />
			<cmd name="view" method="cmdView" formname="sample"/>
			<cmd name="edit" method="cmdEdit" formname="sample" />
			<cmd name="add" method="cmdAdd" formname="sample" />
			<cmd name="update" method="cmdUpdate" formname="sample" from="edit" authtype="U" />
			<cmd name="insert" method="cmdInsert" from="update" authtype="C"/>
		</cmds>
		<forms>
			<form name="sample" bundle="sample">
				<input name="title" message="form.title" type="text" >
					<constraint validatorName="required"/>
					<constraint validatorName="maxlength" value="10b"/>
					<constraint validatorName="minlength" value="4b"/>
				</input>
				<input name="reg_dt" message="">
				</input>
			</form>
		</forms>		
	</action>
	<action uri="excelupload.do" type="miraenet.app.excelUploader.ExcelUpload" 
		desc="excel Upload" 
		title="sample title" default="default">
		<action-view>
			<view-info name="default" uri="/WEB-INF/jsp/_sample/excelupload/default.jsp" useTemplate="inner" />
			
		</action-view>	
		<cmds>
			<cmd name="default" method="cmdDefault" />
			<cmd name="sample" method="cmdSample" />
		</cmds>
		
	</action>
</configuration>

=== bluevlad/Java/MAF_JDK1.5/WebContent/WEB-INF/maf-action/intranet.homepage.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE maf-command PUBLIC
         "-//Miranet//DTD maf-command config XML V1.0//EN"
         "mvc-configuration.dtd">
<configuration>
	<global-view></global-view>
	<action uri="codeGroup.do" type="miraenet.app.codemanager.CodeGroupAction" desc="코드그룹관리" title="코드그룹관리" default="list">
		<action-view>
			<view-info name="list" uri="/WEB-INF/jsp/mafapp/codemanager/codegroup/list.jsp" useTemplate="www" />
			<view-info name="view" uri="/WEB-INF/jsp/mafapp/codemanager/codegroup/view.jsp" useTemplate="www" />
			<view-info name="edit" uri="/WEB-INF/jsp/mafapp/codemanager/codegroup/edit.jsp" useTemplate="www" />
			<view-info name="add" uri="/WEB-INF/jsp/mafapp/codemanager/codegroup/edit.jsp" useTemplate="www" />
		</action-view>
		<cmds>
			<cmd name="list" method="cmdList" />
			<cmd name="view" method="cmdView" />
			<cmd name="edit" method="cmdEdit" />
			<cmd name="add" method="cmdAdd" />
			<cmd name="update" method="cmdUpdate" />
			<cmd name="insert" method="cmdInsert" />
			<cmd name="delete" method="cmdDelete" />
		</cmds>
	</action>
	<action uri="codeMng.do" type="miraenet.app.codemanager.CodeMngAction" desc="코드관리" title="코드관리" default="default"
		debug="true">
		<action-view>
			<view-info name="default" uri="/WEB-INF/jsp/mafapp/codemanager/codemng/default.jsp" useTemplate="www" />
			<view-info name="list" uri="/WEB-INF/jsp/mafapp/codemanager/codemng/list.jsp" useTemplate="inner_frame" />
			<view-info name="edit" uri="/WEB-INF/jsp/mafapp/codemanager/codemng/edit.jsp" useTemplate="inner_frame" />
			<view-info name="gedit" uri="/WEB-INF/jsp/mafapp/codemanager/codemng/gedit.jsp" useTemplate="inner_frame" />
		</action-view>
		<cmds>
			<cmd name="default" method="cmdDefault" />
			<cmd name="list" method="cmdList" />
			<cmd name="gadd" method="cmdGAdd" />
			<cmd name="ginsert" method="cmdGInsert" />
			<cmd name="gedit" method="cmdGEdit" />
			<cmd name="gupdate" method="cmdGUpdate" />
			<cmd name="gdelete" method="cmdGDelete" />
			<cmd name="add" method="cmdAdd" />
			<cmd name="insert" method="cmdInsert" />
			<cmd name="edit" method="cmdEdit" />
			<cmd name="update" method="cmdUpdate" />
			<cmd name="delete" method="cmdDelete" />
		</cmds>
	</action>
	<action uri="MenuAdmin.do" type="miraenet.app.siteManager.MenuAdmin" title="메뉴관리" desc="메뉴관리" default="default" debug="true">
		<action-view>
			<view-info name="default" uri="/WEB-INF/jsp/mafapp/sitemanager/menuadmin/menu_admin.jsp" useTemplate="www" />
			<view-info name="tree" uri="/WEB-INF/jsp/mafapp/sitemanager/menuadmin/menu_tree.jsp" useTemplate="inner_frame" />
			<view-info name="edit" uri="/WEB-INF/jsp/mafapp/sitemanager/menuadmin/menu_edit.jsp" useTemplate="inner_frame" />
			<view-info name="write" uri="/WEB-INF/jsp/mafapp/sitemanager/menuadmin/menu_edit.jsp" useTemplate="inner_frame" />
		</action-view>
		<cmds>
			<cmd name="default" method="cmdDefault" authtype="R" />
			<cmd name="tree" method="cmdTree" authtype="R" />
			<cmd name="add" method="cmdAdd" authtype="C" />
			<cmd name="edit" method="cmdEdit" authtype="U" />
			<cmd name="update" method="cmdUpdate" authtype="U" />
			<cmd name="insert" method="cmdInsert" authtype="C" />
			<cmd name="delete" method="cmdDelete" authtype="D" />
		</cmds>
	</action>
	<action uri="MenuAuth.do" type="miraenet.app.siteManager.MenuAuthAdmin" title="권한관리" desc="권한관리" default="default">
		<action-view>
			<view-info name="default" uri="/WEB-INF/jsp/mafapp/sitemanager/authadmin/auth_admin.jsp" useTemplate="www" />
			<view-info name="tree" uri="/WEB-INF/jsp/mafapp/sitemanager/authadmin/auth_tree.jsp" useTemplate="inner_frame" />
			<view-info name="edit" uri="/WEB-INF/jsp/mafapp/sitemanager/authadmin/auth_edit.jsp" useTemplate="inner_frame" />
		</action-view>
		<cmds>
			<cmd name="default" method="cmdDefault" />
			<cmd name="tree" method="cmdTree" />
			<cmd name="edit" method="cmdEdit" />
			<cmd name="update" method="cmdUpdate" />
		</cmds>
	</action>
	<action uri="holiday.do" type="miraenet.app.siteManager.HolidayAction" desc="휴일관리" title="휴일관리" default="list">
		<action-view>
			<view-info name="list" uri="/WEB-INF/jsp/mafapp/sitemanager/holiday/list.jsp" useTemplate="inner" />
			<view-info name="edit" uri="/WEB-INF/jsp/mafapp/sitemanager/holiday/edit.jsp" useTemplate="inner" />
		</action-view>
		<cmds>
			<cmd name="list" method="cmdList" />
			<cmd name="edit" method="cmdEdit" />
			<cmd name="update" method="cmdUpdate" />
			<cmd name="insert" method="cmdInsert" />
			<cmd name="add" method="cmdAdd" />
			<cmd name="delete" method="cmdDelete" />
		</cmds>
	</action>
	<action uri="AuthAdmin.do" type="miraenet.app.siteManager.AuthAction" desc="사용자권한관리" title="사용자권한관리" default="list"
		debug="true">
		<action-view>
			<view-info name="list" uri="/WEB-INF/jsp/mafapp/sitemanager/role/list.jsp" useTemplate="www" />
			<view-info name="edit" uri="/WEB-INF/jsp/mafapp/sitemanager/role/edit.jsp" useTemplate="www" />
		</action-view>
		<cmds>
			<cmd name="list" method="cmdList" />
			<cmd name="edit" method="cmdEdit" />
			<cmd name="update" method="cmdUpdate" />
			<cmd name="insert" method="cmdInsert" />
			<cmd name="add" method="cmdAdd" />
			<cmd name="delete" method="cmdDelete" />
		</cmds>
	</action>
	<action uri="LangManager.do" type="miraenet.app.siteManager.LangManagerAction" desc="사용언어 관리" title="사용언어 관리" default="list"
		debug="true">
		<action-view>
			<view-info name="list" uri="/WEB-INF/jsp/mafapp/langmanager/list.jsp" useTemplate="www" />
		</action-view>
		<cmds>
			<cmd name="list" method="cmdList" formname="frm1" authtype="R" />
			<cmd name="update" method="cmdUpdate" formname="frm1" authtype="U" />
		</cmds>
		<forms>
			<form name="frm1" bundle="table.maf_lang_iso639_1">
				<input name="code" message="code" type="text"></input>
				<input name="code2" message="code2" type="text"></input>
				<input name="allnames" message="allnames" type="text"></input>
				<input name="active_yn" bundle="table._common" message="field.active_yn" type="text"></input>
				<input name="local_name" message="local_name" type="text"></input>
				<input name="reg_nm" message="reg_nm" type="text" bundle="common"></input>
			</form>
		</forms>
	</action>
	<action uri="ResourceManager.do" type="miraenet.app.resource.ResourceManagerAction" desc="다국어 메시지관리" default="list"
		debug="true">
		<action-view>
			<view-info name="list" uri="/WEB-INF/jsp/mafapp/resourcemanager/list.jsp" useTemplate="www" />
			<view-info name="view" uri="/WEB-INF/jsp/mafapp/resourcemanager/view.jsp" useTemplate="www" />
			<view-info name="excel" uri="/WEB-INF/reports/excel/excel_resource.xml" type="excel" />
		</action-view>
		<cmds>
			<cmd name="list" method="cmdList" formname="frm1" authtype="R" />
			<cmd name="view" method="cmdView" formname="frm1" authtype="R" />
			<cmd name="update" method="cmdUpdate" formname="frm1" authtype="U" />
			<cmd name="updateOne" method="cmdUpdateOne" formname="frm1" authtype="U" />
			<cmd name="downloadExcel" method="cmdDownloadExcel" formname="frm1" authtype="R" />
			<cmd name="upExcel" method="cmdUploadExcel" formname="frm1" authtype="U" />
		</cmds>
		<forms>
			<form name="frm1" bundle="table.maf_lang_iso639_1">
				<input name="code" message="code" type="text"></input>
				<input name="code2" message="code2" type="text"></input>
				<input name="allnames" message="allnames" type="text"></input>
				<input name="active_yn" bundle="table._common" message="field.active_yn" type="text"></input>
				<input name="local_name" message="local_name" type="text"></input>
				<input name="reg_nm" message="reg_nm" type="text" bundle="common"></input>
			</form>
		</forms>
	</action>
	<action uri="dbsyncconfig.do" type="miraenet.app.dbsync.ShowConfig" title="dbsync정보보기" desc="dbsync정보보기">
		<action-view>
			<view-info name="default" uri="/WEB-INF/jsp/mafapp/dbsync/dbsyncstatus.jsp" />
		</action-view>
	</action>
</configuration>

=== bluevlad/Java/MAF_JDK1.5/WebContent/WEB-INF/maf-action/dbadmin.xml
<?xml version="1.0" encoding="euc-kr"?>
<!DOCTYPE maf-command PUBLIC
         "-//Miranet//DTD maf-command config XML V1.0//EN"
         "mvc-configuration.dtd">
<configuration>
	<template-list>
		<template-info name="inner" uri="/WEB-INF/jsp/mafapp/dbadmin/_inner.jsp" />
		<template-info name="contents" uri="/WEB-INF/jsp/mafapp/dbadmin/_contents.jsp" />
		<template-info name="procinfo" uri="/WEB-INF/jsp/mafapp/dbadmin/_procinfo.jsp" />
	</template-list>

	<global-view>
	</global-view>

	<action uri="default.do" 	type="miraenet.app.dbadmin.actions.Default" >
		<action-view>
			<view-info name="default" uri="/WEB-INF/jsp/mafapp/dbadmin/index.jsp"  />

		</action-view>
	</action>
	<action uri="top.do" 	type="miraenet.app.dbadmin.actions.Top">
		<action-view>
			<view-info name="top" uri="/WEB-INF/jsp/mafapp/dbadmin/top.jsp" useTemplate="inner" />
		</action-view>		
	</action>
	<action uri="mssqltable.do" 	type="maf.modules.dbadmin.actions.MSSqlTable">
		<action-view>
			<view-info name="list" uri="/WEB-INF/jsp/mafapp/dbadmin/sqltable.jsp" />
		</action-view>
	</action>
	<action uri="tableList.do" 	type="miraenet.app.dbadmin.actions.TableList">
		<action-view>
			<view-info name="tableList" uri="/WEB-INF/jsp/mafapp/dbadmin/table_list.jsp" useTemplate="inner" />		
		</action-view>	
	</action>
	
	<action uri="tabsinfo.do" 	type="miraenet.app.dbadmin.actions.TableInfo" default="column">
		<action-view>
			
		
			<view-info name="sql" uri="/WEB-INF/jsp/mafapp/dbadmin/sql.jsp" useTemplate="contents" />
			<view-info name="form" uri="/WEB-INF/jsp/mafapp/dbadmin/form.jsp" useTemplate="contents" />
			<view-info name="procInfo" uri="/WEB-INF/jsp/mafapp/dbadmin/proc_info.jsp" useTemplate="procinfo" />
			<view-info name="indexInfo" uri="/WEB-INF/jsp/mafapp/dbadmin/index_info.jsp" useTemplate="contents" />
			<view-info name="javabean" uri="/WEB-INF/jsp/mafapp/dbadmin/java_bean.jsp" useTemplate="contents" />
			<view-info name="javastmt" uri="/WEB-INF/jsp/mafapp/dbadmin/java_stmt.jsp" useTemplate="contents" />	



			<view-info name="JavaAction" uri="/WEB-INF/jsp/mafapp/dbadmin/tpl01/JavaAction.jsp" useTemplate="contents" />
			<view-info name="JavaDB" uri="/WEB-INF/jsp/mafapp/dbadmin/tpl01/JavaDB.jsp" useTemplate="contents" />
			<view-info name="JavaActionConfig" uri="/WEB-INF/jsp/mafapp/dbadmin/tpl01/JavaActionConfig.jsp" useTemplate="contents" />
			<view-info name="JavaResourceConfig" uri="/WEB-INF/jsp/mafapp/dbadmin/tpl01/JavaResourceConfig.jsp" useTemplate="contents" />
			<view-info name="JspList" uri="/WEB-INF/jsp/mafapp/dbadmin/tpl01/JspList.jsp" useTemplate="contents" />
			<view-info name="JspView" uri="/WEB-INF/jsp/mafapp/dbadmin/tpl01/JspView.jsp" useTemplate="contents" />
			<view-info name="JspEdit" uri="/WEB-INF/jsp/mafapp/dbadmin/tpl01/JspEdit.jsp" useTemplate="contents" />
			<view-info name="JspAdd" uri="/WEB-INF/jsp/mafapp/dbadmin/tpl01/JspAdd.jsp" useTemplate="contents" />
			<view-info name="ExcelUpload" uri="/WEB-INF/jsp/mafapp/dbadmin/tpl01/excelupload.jsp" useTemplate="contents" />
			
		</action-view>
		<cmds>
			<cmd name="sql" method="getSqlInfo"/>
			<cmd name="beans" method="getBeans"/>
			<cmd name="SQL" method="getSQL"/>
			<cmd name="STMT" method="getSTMT"/>
			<cmd name="index" method="getIndex"/>
			<cmd name="excel" method="getExcel"/>
			<cmd name="form" method="getForm"/>

			<cmd name="JavaAction" method="getJavaSource"/>
			<cmd name="JavaDB" method="getJavaSource"/>
			<cmd name="JavaActionConfig" method="getJavaSource"/>
			<cmd name="JavaResourceConfig" method="getJavaSource"/>
			<cmd name="JspList" method="getJavaSource"/>
			<cmd name="JspView" method="getJavaSource"/>
			<cmd name="JspEdit" method="getJavaSource"/>
			<cmd name="JspAdd" method="getJavaSource"/>
			<cmd name="ExcelUpload" method="getJavaSource"/>

		</cmds>
	</action>
	<action uri="procinfo.do" 	type="miraenet.app.dbadmin.actions.ProcInfo" />
	<action uri="dbsyncconfig.do" type="miraenet.app.dbsync.ShowConfig"  title="dbsync정보보기" desc="dbsync정보보기" default="default">
		
		<action-view>
			<view-info  name="default" uri="/WEB-INF/jsp/mafapp/dbsync/dbsyncstatus.jsp" />
		</action-view>
		<cmds>
			<cmd name="default" method="cmdDefault"/>
			<cmd name="start" method="cmdStart"/>
			<cmd name="stop" method="cmdStop"/>
		</cmds>
	</action>	
</configuration>

=== bluevlad/Java/MAF_JDK1.4/WebContent/WEB-INF/maf-action/pager.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE maf-command PUBLIC
         "-//Miranet//DTD maf-command config XML V1.0//EN"
         "mvc-configuration.dtd">
<configuration>
	<template-list>
		<template-info name="inner" uri="/WEB-INF/jsp/mafapp/pager/_layout.jsp" />
	</template-list>


	
	<action uri="default.do" type="miraenet.app.pager.PagerAction" desc="쪽지" title="쪽지" default="listRcv">
		<action-view>
			<view-info name="listRcv" uri="/WEB-INF/jsp/mafapp/pager/listRcv.jsp" useTemplate="inner" />
			<view-info name="listSnd" uri="/WEB-INF/jsp/mafapp/pager/listSnd.jsp" useTemplate="inner" />
			<view-info name="msgViewRcv" uri="/WEB-INF/jsp/mafapp/pager/msgViewRcv.jsp" useTemplate="inner" />
			<view-info name="msgViewSnd" uri="/WEB-INF/jsp/mafapp/pager/msgViewSnd.jsp" useTemplate="inner" />
			<view-info name="edit" uri="/WEB-INF/jsp/mafapp/pager/edit.jsp" useTemplate="inner" />
			<view-info name="msgWrite" uri="/WEB-INF/jsp/mafapp/pager/msgWrite.jsp" useTemplate="inner" />
			<view-info name="addressBook" uri="/WEB-INF/jsp/mafapp/pager/addressBook.jsp" useTemplate="inner" />
		</action-view>
		<cmds>
			<cmd name="listRcv" method="cmdListRcv" formname="frm1" authtype="R" />
			<cmd name="listSnd" method="cmdListSnd" formname="frm1" authtype="R" />
			<cmd name="deleteRcv" method="cmdDeleteRcv" formname="frm1" authtype="D" />
			<cmd name="deleteSnd" method="cmdDeleteSnd" formname="frm1" authtype="D" />
			<cmd name="msgViewSnd" method="cmdMsgViewSnd" formname="frm1" authtype="R" />
			<cmd name="msgViewRcv" method="cmdMsgViewRcv" formname="frm1" authtype="R" />
			<cmd name="edit" method="cmdEdit" formname="frm1" authtype="U" />
			<cmd name="update" method="cmdUpdate" formname="frm1" from="edit" authtype="U" />
			<cmd name="sendMsg" method="cmdSendMsg" formname="frm1" from="update" authtype="C" />
			<cmd name="msgWrite" method="cmdMsgWrite" formname="frm1" from="update" authtype="C" />
			<cmd name="grpMsgWrite" method="cmdGrpMsgWrite" formname="frm1" from="update" authtype="C" />
			<cmd name="addressBook" method="cmdAddressBook" formname="frm2"  />
			
		</cmds>
		<forms>
			<form name="frm1" bundle="mafpager">
					<input name="msg_no" message="form.msg_no" type="text" >
						<constraint validatorName="required"/>
					</input>
					<input name="msg_rcv_userid" message="form.msg_rcv_userid" type="text" >
						<constraint validatorName="required"/>
					</input>
					<input name="msg_rcv_nm" message="form.msg_rcv_nm" type="text" >
					</input>
					<input name="msg_snd_userid" message="form.msg_snd_userid" type="text" >
					</input>
					<input name="msg_snd_nm" message="form.msg_snd_nm" type="text" >
					</input>
					<input name="msg_title" message="form.msg_title" maxlength="100" type="text" >
						<constraint validatorName="required"/>
					</input>
					<input name="msg_info" message="form.msg_info" type="textarea" >
						<constraint validatorName="required"/>
					</input>
					<input name="file_name" message="form.file_name" type="file" >
					</input>
					<input name="msg_dt" message="form.msg_dt" type="text" >
					</input>
					<input name="msg_read_dt" message="form.msg_read_dt" type="text" >
					</input>
					<input name="msg_rcv_isdel" message="form.msg_rcv_isdel" type="text" >
					</input>
					<input name="msg_snd_isdel" message="form.msg_snd_isdel" type="text" >
					</input>
					<input name="update_dt" message="form.update_dt" type="text" >
					</input>
					<input name="update_id" message="form.update_id" type="text" >
					</input>
			</form>		
			<form name="frm2" bundle="mafpager">
				
					<input name="msg_grp_id" message="form.msg_grp_id" type="text" >
						<constraint validatorName="required"/>
					</input>
				
					<input name="msg_grp_nm" message="form.msg_grp_nm" type="text" >
						<constraint validatorName="required"/>
					</input>
				
					<input name="owner_usn" message="form.owner_usn" type="text" >
						<constraint validatorName="required"/>
					</input>
			</form>			
		</forms>
	</action>

</configuration>

=== bluevlad/Java/HKMCA_2008/WebContent/WEB-INF/maf-action/xadmin.board.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE maf-command PUBLIC
         "-//UBQ//DTD maf-command config XML V1.0//EN"
         "mvc-configuration.dtd">
<configuration>
	<global-view>
	</global-view>

    <action uri="boardGrp.do" type="modules.community.mboard.admin.GrpMngAction" title="게시판그룹관리" desc="게시판그룹관리"
     jsppath="/mboard/grp/" default="default">
        <action-view>
            <view-info name="default" uri="default.jsp" useTemplate="www" />
        </action-view>
        <cmds>
            <cmd name="default" method="cmdDefault" />
            <cmd name="update" method="cmdUpdate" />
            <cmd name="insert" method="cmdInsert" />
        </cmds>
    </action>

	<action uri="boardMeta.do" type="modules.community.mboard.admin.MetaMngAction" title="게시판관리" desc="게시판관리"
	 jsppath="/mboard/meta/" default="list" >
		<action-view>
            <view-info name="list" uri="list.jsp" useTemplate="www" />
            <view-info name="add" uri="edit.jsp" useTemplate="www" />
            <view-info name="edit" uri="edit.jsp" useTemplate="www" />
		</action-view>
		<cmds>
			<cmd name="list" method="cmdList" />
            <cmd name="add" method="cmdAdd" />
			<cmd name="edit" method="cmdEdit" />
			<cmd name="update" method="cmdUpdate" />
			<cmd name="insert" method="cmdInsert" />
            <cmd name="delete" method="cmdDelete" />
		</cmds>
	</action>

	<action uri="boardAdmin.do" type="modules.community.mboard.admin.AdminData" title="게시판관리" desc="게시판관리"
	 default="list" jsppath="/mboard/adminData/">
		<action-view>
			<view-info name="default" uri="default.jsp" useTemplate="www" />
			<view-info name="head" uri="head.jsp" useTemplate="www" />
			<view-info name="blank" uri="blank.jsp" useTemplate="www" />
			<view-info name="tree" uri="tree.jsp" useTemplate="www" />
		</action-view>
	</action>
</configuration>
