=== bluevlad/Java/MAF_JDK1.5/WebContent/WEB-INF/maf-action/mvc-configuration.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
	 mvc conrol Configuration
	 Version : 1.0	(2005.03.30)
	 Author : Kim Sang Joon
-->
<!-- 
	configuration is the root element. 
	template-list : 테프릿 이름과 Block(Template-Info)들 정의 
-->
<!ELEMENT configuration (template-list | global-view | action)*>
<!ELEMENT template-list (template-info)*>
<!--
   template block 정보
-->
<!ELEMENT template-info (template-map | site-template)*>
<!ATTLIST template-info
	name 	ID  #REQUIRED 
	uri 	CDATA  #REQUIRED 
	desc 	CDATA #IMPLIED 
	useSiteTemplate 	(true|false) #IMPLIED
>

<!ELEMENT template-map EMPTY>
<!ATTLIST template-map
	name 	CDATA  #REQUIRED 
	uri 	CDATA  #REQUIRED 
>

<!ELEMENT site-template EMPTY>
<!ATTLIST site-template
	site 	CDATA  #REQUIRED 
	uri 	CDATA  #REQUIRED 
>

<!ELEMENT global-view (view-info)*>
<!ELEMENT view-info EMPTY>
<!--
	type : html 일반(default)
	jpdf : JasperPDFView	
-->
<!ATTLIST view-info
	name 		CDATA  #REQUIRED 
	uri 		CDATA  #IMPLIED 
	redirect 	(true|false) #IMPLIED 
	useTemplate CDATA #IMPLIED 
	desc 	CDATA #IMPLIED 
	title 	CDATA #IMPLIED 
	type 	(html|xml|jpdf|excel|json|dummy) #IMPLIED 
>

<!ELEMENT action (aliases | action-view | cmds | forms)*>
<!ELEMENT action-view (view-info)*>
<!--
	jsppath : view단의 기본 path
	단 view의 url이 /로 시작하면 무시된다.
-->
<!ATTLIST action
	uri 	CDATA  	#REQUIRED 
	type 	CDATA  	#REQUIRED 
	desc 	CDATA 	#IMPLIED 
	title 	CDATA 	#IMPLIED 
	default CDATA 	#IMPLIED 
	param CDATA #IMPLIED 
	debug 	(true|false) #IMPLIED 
	jsppath CDATA 	#IMPLIED 
>
<!ELEMENT aliases (alias)*>
<!ELEMENT alias EMPTY>
<!ATTLIST alias
	uri 	CDATA  	#REQUIRED 
	desc 	CDATA 	#IMPLIED 
	title 	CDATA 	#IMPLIED 
	default CDATA 	#IMPLIED 
	param CDATA #IMPLIED 	
>
<!ELEMENT cmds (cmd)*>
<!ELEMENT cmd EMPTY>
<!ATTLIST cmd
	name 	CDATA  	#REQUIRED 
	method 	CDATA  	#REQUIRED 
	from 	CDATA  	#IMPLIED 
	desc 	CDATA 	#IMPLIED 
	formname	CDATA 	#IMPLIED 
	authtype	(C|R|U|D) #IMPLIED
	cmdtype	(java|jsp) #IMPLIED 
>
<!ELEMENT forms (form)*>
<!ELEMENT form (input)*>
<!ATTLIST form
	name 	CDATA  #REQUIRED 
	bundle	CDATA  #IMPLIED
>
<!ELEMENT input (constraint)*>
<!ATTLIST input
	name 	CDATA  #REQUIRED 
	message CDATA  #REQUIRED 
	bundle	CDATA  #IMPLIED
	type	(text|textarea|select|check|radio|file)  #IMPLIED
	codegroup	CDATA  #IMPLIED
	maxlength 	CDATA  #IMPLIED
	arg0	CDATA  #IMPLIED
	arg1	CDATA  #IMPLIED
	arg2	CDATA  #IMPLIED
	required (true|false) #IMPLIED 
>
<!ELEMENT constraint EMPTY>
<!ATTLIST constraint
	validatorName 	CDATA  #REQUIRED 
	value	CDATA  #IMPLIED
	arg0	CDATA  #IMPLIED
	arg1	CDATA  #IMPLIED
	arg2	CDATA  #IMPLIED
>

=== bluevlad/Java/HKMCA_2008/WebContent/WEB-INF/maf-action/xadmin.product.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE maf-command PUBLIC
         "-//UBQ//DTD maf-command config XML V1.0//EN"
         "mvc-configuration.dtd">
<configuration>
	<global-view></global-view>
    
<action uri="PrdMng.do" type="modules.xadmin.product.PrdMngAction" desc="제품관리" title="제품관리"
    jsppath="/WEB-INF/jsp/xadmin/product/prdmng/" default="list">
	<action-view>
		<view-info name="list" uri="list.jsp" useTemplate="www" />
        <view-info name="add" uri="edit.jsp" useTemplate="www" />
		<view-info name="edit" uri="edit.jsp" useTemplate="www" />
	</action-view>
	<cmds>
		<cmd name="list" method="cmdList" formname="frm1" />
		<cmd name="add" method="cmdAdd" formname="frm1" />
		<cmd name="edit" method="cmdEdit" formname="frm1" />
        <cmd name="insert" method="cmdInsert" />
		<cmd name="update" method="cmdUpdate" />
		<cmd name="delete" method="cmdDelete" />
	</cmds>
    <forms>
        <form name="frm1" bundle="product">
            <input name="cat_cd" message="cat_cd" type="text"/>
            <input name="cat_nm" message="cat_nm" type="text" />
	        <input name="prd_cd" message="prd_cd" type="text"/>
            <input name="prd_nm" message="prd_nm" type="text" />
            <input name="p_cat_cd" message="p_cat_cd" type="text"/>
            <input name="p_cat_nm" message="p_cat_nm" type="text"/>
	        <input name="imp_type" message="imp_type" type="text" />
            <input name="prd_type" message="prd_type" type="text" />
            <input name="company" message="company" type="text" />
	        <input name="prd_price" message="prd_price" type="text" />
            <input name="nor_price" message="nor_price" type="text" />
            <input name="dis_price" message="dis_price" type="text" />
            <input name="prd_desc" message="prd_desc" type="text" />
            <input name="dis_abt_cd" message="dis_abt" type="text" bundle="table.dis_abt" />
	        <input name="reg_dt" message="reg_dt" type="text" />
            <input name="active_yn" bundle="common" message="active_yn" type="text"></input>
        </form>
    </forms>
</action>
	
<action uri="comMng.do" type="modules.xadmin.product.PrdCompanyMngAction" desc="업체관리" title="업체관리"
    jsppath="/WEB-INF/jsp/xadmin/product/prdcom/" default="list">
    <action-view>
        <view-info name="list" uri="list.jsp" useTemplate="www" />
        <view-info name="add" uri="edit.jsp" useTemplate="www" />
        <view-info name="edit" uri="edit.jsp" useTemplate="www" />
    </action-view>
    <cmds>
        <cmd name="list" method="cmdList" formname="frm1" />
        <cmd name="add" method="cmdAdd" formname="frm1" />
        <cmd name="edit" method="cmdEdit" formname="frm1" />
        <cmd name="insert" method="cmdInsert" />
        <cmd name="update" method="cmdUpdate" />
        <cmd name="delete" method="cmdDelete" />
    </cmds>
    <forms>
        <form name="frm1" bundle="product">
			<input name="com_cd" message="com_cd" type="text" required="true"/>
			<input name="com_nm" message="com_nm" type="text" />
			<input name="com_desc" message="com_desc" type="text" />
			<input name="com_usr" message="com_usr" type="text" />
			<input name="com_phone" message="com_phone" type="text" />
			<input name="com_zipcode" message="com_zipcode" type="text" />
			<input name="com_addr" message="com_addr" type="text" />
			<input name="com_org_img" message="com_org_img" type="text" />
			<input name="com_new_img" message="com_new_img" type="text" />
			<input name="com_banner_yn" message="com_banner_yn" type="text" />
			<input name="com_url" message="com_url" type="text" />
            <input name="active_yn" bundle="common" message="active_yn" type="text"></input>
        </form>
    </forms>
</action>
    
<action uri="catalogMng.do" type="modules.xadmin.product.CatalogMngAction" title="e-카탈로그 관리" desc="e-카탈로그 관리"
   jsppath="/WEB-INF/jsp/xadmin/product/catalog/" default="default">
    <action-view>
        <view-info name="default" uri="default.jsp" useTemplate="www" />
        <view-info name="tree" uri="tree.jsp" useTemplate="inner_frame" />
        <view-info name="edit" uri="edit.jsp" useTemplate="inner_frame" />
        <view-info name="write" uri="edit.jsp" useTemplate="inner_frame" />
    </action-view>
    <cmds>
        <cmd name="default" method="cmdDefault" />
        <cmd name="tree" method="cmdTree" authtype="R" />
        <cmd name="add" method="cmdAdd" formname="frm1" />
        <cmd name="edit" method="cmdEdit" formname="frm1" />
        <cmd name="insert" method="cmdInsert" />
        <cmd name="update" method="cmdUpdate" />
        <cmd name="delete" method="cmdDelete" />
    </cmds>
    <forms>
        <form name="frm1" bundle="table.catalog">
            <input name="cat_id" message="cat_id" type="text"/>
            <input name="cat_nm" message="cat_nm" type="text" />
            <input name="comments" message="comments" type="text"/>
            <input name="lvl" message="lvl" type="text" />
            <input name="p_cat_id" message="p_cat_id" type="text"/>
            <input name="s_img" message="s_img" type="text"/>
            <input name="l_img" message="l_img" type="text" />
            <input name="viw" message="viw" type="text" />
        </form>
    </forms>
</action>

<action uri="prdReqMng.do" type="modules.xadmin.product.PrdReqMngAction" title="키즈보이스신청관리" desc="키즈보이스신청관리"
	jsppath="/WEB-INF/jsp/xadmin/product/prdreqmng/" default="list">
	<action-view>
		<view-info name="list" uri="list.jsp" useTemplate="www" />
		<view-info name="edit" uri="edit.jsp" useTemplate="www" />
        <view-info name="add" uri="edit.jsp" useTemplate="www" />
	</action-view>
	<cmds>
        <cmd name="list" method="cmdList" formname="frm1" />
        <cmd name="add" method="cmdAdd" formname="frm1" />
		<cmd name="edit" method="cmdEdit" formname="frm1" />
        <cmd name="insert" method="cmdInsert" />
		<cmd name="update" method="cmdUpdate" />
		<cmd name="delete" method="cmdDelete" />
	</cmds>
    <forms>
        <form name="frm1" bundle="product">
            <input name="prd_cd" message="prd_cd" type="text" required="true"/>
            <input name="prd_nm" message="prd_nm" type="text" />
            <input name="prd_price" message="prd_price" type="text" />
            <input name="reg_dt" message="reg_dt" type="text" />
            <input name="sup_area" message="sup_area" type="text" />
            <input name="sup_cnt" message="sup_cnt" type="text" />
            <input name="area" message="area" type="text" />
            <input name="req_user" message="req_user" type="text" />
            <input name="req_phone" message="req_phone" type="text" />
            <input name="req_mobile" message="req_mobile" type="text" />
            <input name="req_addr" message="req_addr" type="text" />
            <input name="dpt_user" message="dpt_user" type="text" />
            <input name="dpt_phone" message="dpt_phone" type="text" />
            <input name="dpt_mobile" message="dpt_mobile" type="text" />
            <input name="sup_dt" message="sup_dt" type="text" />
            <input name="req_type" message="req_type" type="text" />
            <input name="req_price" message="req_price" type="text" />
            <input name="comments" message="comments" type="text" />
        </form>
    </forms>
</action>
	
<action title="보급통계" uri="PrdStat.do" type="modules.xadmin.product.PrdStatAction"
    jsppath="/WEB-INF/jsp/xadmin/product/prdstat" default="prd" >
    <action-view>
        <view-info name="prd" uri="prd.jsp" useTemplate="www" />
        <view-info name="area" uri="area.jsp" useTemplate="www" />
        <view-info name="kids" uri="kids.jsp" useTemplate="www" />
    </action-view>
    <cmds>
        <cmd name="prd" method="cmdPrd" formname="frm1" />
        <cmd name="area" method="cmdArea" formname="frm1" />
    </cmds>
    <forms>
        <form name="frm1" bundle="product">
            <input name="prd_nm" message="prd_nm" type="text" />
            <input name="area" message="area" type="text" />
            <input name="prd_price" message="prd_price" type="text" />
            <input name="prd_cnt" message="prd_cnt" type="text"/>
            <input name="prd_req_sum" message="prd_req_sum" type="text"/>
            <input name="prd_prd_sum" message="prd_prd_sum" type="text"/>
        </form>
    </forms>
</action>

</configuration>

=== bluevlad/Java/MAF_JDK1.5/WebContent/WEB-INF/maf-action/survey.admin.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE maf-resource PUBLIC
         "-//Miranet//DTD maf-command config XML V1.0//EN"
         "mvc-configuration.dtd">
<configuration>
	<global-view></global-view>
	<action uri="bank.do" type="modules.survey.admin.BankManagerAction" desc="설문은행관리" default="list">
		<action-view>
			<view-info name="list" uri="/WEB-INF/jsp/survey/admin/bankmanager/list.jsp" useTemplate="www" />
			<view-info name="edit" uri="/WEB-INF/jsp/survey/admin/bankmanager/edit.jsp" useTemplate="www" />
			<view-info name="add" uri="/WEB-INF/jsp/survey/admin/bankmanager/add.jsp" useTemplate="www" />
			<view-info name="editLang" uri="/WEB-INF/jsp/survey/admin/bankmanager/editLang.jsp" useTemplate="www" />
		</action-view>
		<cmds>
			<cmd name="list" method="cmdList" formname="frm1" authtype="R" />
			<cmd name="edit" method="cmdEdit" formname="frm1" authtype="U" />
			<cmd name="update" method="cmdUpdate" formname="frm1" from="edit" authtype="U" />
			<cmd name="insert" method="cmdInsert" formname="frm1" from="update" authtype="C" />
			<cmd name="add" method="cmdAdd" formname="frm1" from="update" authtype="C" />
			<cmd name="delete" method="cmdDelete" formname="frm1" from="delete" authtype="D" />
			<cmd name="editLang" method="cmdEditLang" formname="frm1" authtype="U" />
		</cmds>
		<forms>
			<form name="frm1" bundle="table.survey_bank">
				<input name="queid" message="queid" type="text" required="true" />
				<input name="qweowner" message="qweowner" type="text" required="true" />
				<input name="quetitle" message="quetitle" type="text" />
				<input name="quecount" message="quecount" type="text" />
				<input name="quetype" message="quetype" type="text" required="true" />
				<input name="update_dt" bundle="table._common" message="field.update_dt" type="text" />
				<input name="active_yn" bundle="common" message="select.active" type="text" />
			</form>
		</forms>
	</action>
	
	<action uri="setmanager.do" type="modules.survey.admin.SetManagerAction" desc="설문 Set 관리" default="list">
		<action-view>
			<view-info name="list" uri="/WEB-INF/jsp/survey/admin/setmanager/list.jsp" useTemplate="www" />
			<view-info name="view" uri="/WEB-INF/jsp/survey/admin/setmanager/view.jsp" useTemplate="www" />
			<view-info name="edit" uri="/WEB-INF/jsp/survey/admin/setmanager/edit.jsp" useTemplate="www" />
			<view-info name="add" uri="/WEB-INF/jsp/survey/admin/setmanager/add.jsp" useTemplate="www" />
		</action-view>
		<cmds>
			<cmd name="list" method="cmdList" formname="frm1" authtype="R" />
			<cmd name="view" method="cmdView" formname="frm1" authtype="R" />
			<cmd name="edit" method="cmdEdit" formname="frm1" authtype="U" />
			<cmd name="update" method="cmdUpdate" formname="frm1" from="edit" authtype="U" />
			<cmd name="updateItems" method="cmdUpdateItems" formname="frm1" from="edit" authtype="U" />
			<cmd name="insert" method="cmdInsert" formname="frm1" from="update" authtype="C" />
			<cmd name="add" method="cmdAdd" formname="frm1" from="update" authtype="C" />
			<cmd name="delete" method="cmdDelete" formname="frm1" from="delete" authtype="D" />
			
		</cmds>
		<forms>
			<form name="frm1" bundle="table.survey_set">
				<input name="setid" message="setid" type="text" required="true" />
				<input name="setowner" message="setowner" type="text" required="true" />
				<input name="settitle" message="settitle" type="text" />
				<input name="surveytype" message="surveytype" bundle="table.survey_mst" type="text" />
				<input name="setdesc" message="setdesc" type="text" />
				<input name="reg_usn" bundle="table._common" message="field.reg_usn" type="text" />
				<input name="reg_dt" bundle="table._common" message="field.reg_dt" type="text" />
				<input name="update_dt" bundle="table._common" message="field.update_dt" type="text" />
				<input name="update_usn" bundle="table._common" message="field.update_usn" type="text" />
				<input name="active_yn" bundle="common" message="select.use" type="text" required="true" />
				<input name="queid" message="queid" bundle="table.exm_bank" type="text" />
				<input name="quetitle" message="quetitle" bundle="table.exm_bank" type="text" />
			</form>
		</forms>
	</action>
	
	<action uri="surveymanager.do" type="modules.survey.admin.SurveyManagerAction" desc="설문관리"
		default="list" jsppath="/WEB-INF/jsp/survey/admin/surveymanager/">
		<action-view>
			<view-info name="list" uri="list.jsp" useTemplate="www" />
			<view-info name="view" uri="view.jsp" useTemplate="www" />
			<view-info name="edit" uri="edit.jsp" useTemplate="www" />
			<view-info name="add" uri="add.jsp" useTemplate="www" />
			<view-info name="excel" uri="excel.jsp" />
		</action-view>
		<cmds>
			<cmd name="list" method="cmdList" formname="frm1" authtype="R" />
			<cmd name="view" method="cmdView" formname="frm1" authtype="R" />
			<cmd name="edit" method="cmdEdit" formname="frm1" authtype="U" />
			<cmd name="update" method="cmdUpdate" formname="frm1" from="edit" authtype="U" />
			<cmd name="insert" method="cmdInsert" formname="frm1" from="update" authtype="C" />
			<cmd name="add" method="cmdAdd" formname="frm1" from="update" authtype="C" />
			<cmd name="delete" method="cmdDelete" formname="frm1" from="delete" authtype="D" />
			<cmd name="excel" method="cmdExcel" formname="frm1" authtype="R" />
		</cmds>
		<forms>
			<form name="frm1" bundle="table.survey_mst">
				<input name="surveyid" message="surveyid" type="text" required="true" />
				<input name="surveyowner" message="surveyowner" type="text" required="true" />
				<input name="surveytitle" message="surveytitle" type="text" />
				<input name="surveydesc" message="surveydesc" type="text" />
				<input name="survey_sdat_t1" message="survey_sdat_t1" type="text" />
				<input name="survey_edat_t1" message="survey_edat_t1" type="text" />
				<input name="surveytype" message="surveytype" type="text" />
				<input name="region" message="region" type="text" bundle="table.bas_org" />
				<input name="org_type" message="org_type" type="text" bundle="table.bas_org" />
				<input name="userid" message="userid" type="text" bundle="table.maf_user" />
				<input name="nm" message="nm" type="text" bundle="table.maf_user" />
				<input name="org_name" message="org_name" type="text" bundle="table.bas_org" />
				<input name="setid" message="setid" type="text" bundle="table.survey_set" />
				<input name="setowner" message="setowner" type="text" bundle="table.survey_set" />
				<input name="settitle" message="settitle" type="text" bundle="table.survey_set" />
				<input name="reg_usn" bundle="table._common" message="field.reg_usn" type="text" />
				<input name="reg_dt" bundle="table._common" message="field.reg_dt" type="text" />
				<input name="update_dt" bundle="table._common" message="field.update_dt" type="text" />
				<input name="update_usn" bundle="table._common" message="field.update_usn" type="text" />
				<input name="active_yn" bundle="common" message="select.use" type="text" required="true" />
			</form>
		</forms>
	</action>
	
	<action uri="setchoose.do" type="modules.survey.admin.SetChooseAction" desc="설문 Set 선택" title="설문 Set 선택" default="list"
		jsppath="/WEB-INF/jsp/survey/admin/setchoose/">
		<action-view>
			<view-info name="list" uri="list.jsp" useTemplate="popup" />
			<view-info name="view" uri="view.jsp" useTemplate="popup" />
		</action-view>
		<cmds>
			<cmd name="list" method="cmdList" formname="frm1" authtype="R" />
			<cmd name="view" method="cmdView" formname="frm1" authtype="R" />
		</cmds>
		<forms>
			<form name="frm1" bundle="table.exm_set">
				<input name="setid" message="setid" type="text" required="true" />
				<input name="setowner" message="setowner" type="text" required="true" />
				<input name="settitle" message="settitle" type="text" />
				<input name="exmtype" message="exmtype" bundle="table.exm_mst" type="text" />
				<input name="setdesc" message="setdesc" type="text" />
				<input name="exmtime" message="exmtime" type="text" />
				<input name="reg_usn" bundle="table._common" message="field.reg_usn" type="text" />
				<input name="reg_dt" bundle="table._common" message="field.reg_dt" type="text" />
				<input name="update_dt" bundle="table._common" message="field.update_dt" type="text" />
				<input name="update_usn" bundle="table._common" message="field.update_usn" type="text" />
				<input name="active_yn" bundle="common" message="select.use" type="text" required="true" />
				<input name="queid" message="queid" bundle="table.exm_bank" type="text" />
				<input name="quetitle" message="quetitle" bundle="table.exm_bank" type="text" />
				<input name="quescore" message="quescore" bundle="table.exm_bank" type="text" />
				<input name="quelevel" message="quelevel" bundle="table.exm_bank" type="text" required="true" />
				<input name="cat_name" bundle="table.exm_category" message="cat_name" />
			</form>
		</forms>
	</action>
</configuration>

=== bluevlad/Java/MAF_JDK1.5/WebContent/WEB-INF/maf-action/intranet.common.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE maf-command PUBLIC
         "-//Miranet//DTD maf-command config XML V1.0//EN"
         "mvc-configuration.dtd">
<configuration>
	<template-list>

	</template-list>

	<global-view>
	</global-view>
	
	<action uri="intranet.do" type="modules.intranet.intranetAction" desc="Intranet frame구성 " title="Intranet frame" default="index">
		<action-view>
			<view-info name="left" uri="/web_src/intranet/leftMenu.jsp" />
			<view-info name="top" uri="/web_src/intranet/topMenu.jsp" />
			<view-info name="index" uri="/web_src/intranet/frame.jsp" />
		</action-view>
		<cmds>
			<cmd name="left" method="cmdLeftMenu" />
			<cmd name="top" method="cmdTopMenu" />
			<cmd name="index" method="cmdIndex" />
		</cmds>
	</action>
	
	<action uri="codeFind.do" type="modules.app.codeFind.CodeFind" desc="codeFind" title="codeFind" default="list">
		<action-view>
			<view-info name="list" uri="/WEB-INF/jsp/codeFind/codeFind.jsp" useTemplate="popup" />
		</action-view>
		<cmds>
			<cmd name="list" method="cmdList" />
		</cmds>
	</action>	
</configuration>

=== bluevlad/Java/HKMCA_2008/WebContent/WEB-INF/maf-action/member.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE maf-command PUBLIC
         "-//UBQ//DTD maf-command config XML V1.0//EN"
         "mvc-configuration.dtd">
<configuration>
	<global-view></global-view>
    
    <action uri="member.do" type="modules.member.MemberAction" desc="개인정보" title="개인정보"
    jsppath="/WEB-INF/jsp/member/" default="default">
        <action-view>
            <view-info name="default" uri="edit.jsp" useTemplate="etc" />
            <view-info name="edit" uri="edit.jsp" useTemplate="etc" />
        </action-view>
        <cmds>
            <cmd name="default" method="cmdDefault" formname="frm1" />
            <cmd name="edit" method="cmdEdit" formname="frm1" />
            <cmd name="insert" method="cmdInsert" />
            <cmd name="update" method="cmdUpdate" />
            <cmd name="delete" method="cmdDelete" />
        </cmds>
        <forms>
            <form name="frm1" bundle="table.maf_user">
	            <input name="usn" message="usn" type="text" required="true"/>
	            <input name="userid" message="userid" type="text" />
	            <input name="passwd" message="passwd" type="text" />
	            <input name="nm" message="nm" type="text" />
	            <input name="nick_nm" message="nick_nm" type="text" />
	            <input name="nm_eng" message="nm_eng" type="text" />
	            <input name="active_yn" message="active_yn" type="text" required="true"/>
	            <input name="pin" message="pin" type="text" />
	            <input name="pos_nm" message="pos_nm" type="text" />
	            <input name="hp" message="hp" type="text" />
	            <input name="tel" message="tel" type="text" />
	            <input name="fax" message="fax" type="text" />
	            <input name="email" message="email" type="text" />
	            <input name="add" message="add" type="text" />
	            <input name="remarks" message="remarks" type="text" />
	            <input name="org_cd" message="org_cd" type="text" />
                <input name="active_yn" message="table.isuse" type="text" bundle="common"></input>
                <input name="reg_dt" message="table.reg_dt" type="text" bundle="common"></input>
            </form>     
        </forms>
    </action>
    
</configuration>
