=== bluevlad/Java/MAF_JDK1.5/WebContent/WEB-INF/maf-resource/resourceBundle.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
	 mvc conrol Configuration
	 Version : 1.0	(2005.03.30)
	 Author : Kim Sang Joon
-->
<!-- 
	configuration is the root element. 
	template-list : 테프릿 이름과 Block(Template-Info)들 정의 
-->
<!ELEMENT bundle (desctiption | resource)*>
<!ATTLIST bundle
	defaultLocale CDATA #REQUIRED 
	imagePath CDATA #IMPLIED 
	desc 	CDATA #IMPLIED 
>
<!ELEMENT desctiption (#PCDATA)>
<!--
   filename이 정의 되었을경우 imagePath / filename 으로 img 버튼을 만듬 
-->
<!ELEMENT resource (message)*>
<!ATTLIST resource
	key 	ID  #REQUIRED 
	value 	CDATA #IMPLIED 
	type	(text|gif|jpeg) #IMPLIED
	desc 	CDATA #IMPLIED 
	filename CDATA #IMPLIED
	icon CDATA #IMPLIED
>

<!ELEMENT message (#PCDATA)>
<!ATTLIST message
	locale	CDATA  #REQUIRED
	value 	CDATA  #IMPLIED 
	desc 	CDATA #IMPLIED 
	filename CDATA #IMPLIED	
	icon CDATA #IMPLIED
>

=== bluevlad/Java/HKMCA_2008/WebContent/WEB-INF/maf-resource/table.wlc_off_req.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE maf-resource PUBLIC "-//UBQ//DTD maf-command config XML V1.0//EN" "resourceBundle.dtd">

<bundle defaultLocale="ko">
  <resource key="appr_dt" type="text">
    <message locale="en" value="Approval date" />
    <message locale="ko" value="승인일" />
  </resource>
  <resource key="btn.attend_insert" type="text">
    <message locale="en" value="Insert" />
    <message locale="ko" value="출석체크" />
  </resource>
  <resource key="btn.mail_send" type="text">
    <message locale="en" value="Send mail" />
    <message locale="ko" value="메일발송" />
  </resource>
  <resource key="btn.score_insert" type="text">
    <message locale="en" value="Save score (grade)" />
    <message locale="ko" value="점수저장" />
  </resource>
  <resource key="itm_id" type="text">
    <message locale="en" value="Contents ID" />
    <message locale="ko" value="컨텐츠id" />
  </resource>
  <resource key="itm_title" type="text">
    <message locale="en" value="Title" />
    <message locale="ko" value="제목" />
  </resource>
  <resource key="mail" type="text">
    <message locale="en" value="Mail" />
    <message locale="ko" value="메일" />
  </resource>
  <resource key="off_score" type="text">
    <message locale="en" value="Offline Score" />
    <message locale="ko" value="출석점수" />
  </resource>
  <resource key="prf_chk" type="text">
    <message locale="en" value="Instructor attendance check" />
    <message locale="ko" value="강사출석체크" />
  </resource>
  <resource key="req_num" type="text">
    <message locale="en" value="Number of applicants" />
    <message locale="ko" value="신청자수" />
  </resource>
  <resource key="seq_no" type="text">
    <message locale="en" value="No." />
    <message locale="ko" value="일련번호" />
  </resource>
  <resource key="user_chk" type="text">
    <message locale="en" value="User attendance check" />
    <message locale="ko" value="사용자출석체크" />
  </resource>
</bundle>

=== bluevlad/Java/MAF_JDK1.4/WebContent/WEB-INF/maf-resource/table._common.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE maf-command PUBLIC
         "-//Miranet//DTD maf-command config XML V1.0//EN"
         "resourceBundle.dtd">
<bundle defaultLocale="en">
	<desctiption>일반 table의 공통 필드</desctiption>
	<resource key="field.seq" >
		<message locale="ko" value="순서"/>
		<message locale="en" value="Order"/>
	</resource>
	<resource key="field.active_yn" >
		<message locale="ko" value="활성화"/>
		<message locale="en" value="Active"/>
	</resource>
	<resource key="field.update_dt" >
		<message locale="ko" value="최종수정일"/>
		<message locale="en" value="Updated"/>
	</resource>
	<resource key="field.update_usn" >
		<message locale="ko" value="최종수정자"/>
		<message locale="en" value="Updated by "/>
	</resource>
	<resource key="field.reg_dt" >
		<message locale="ko" value="등록일"/>
		<message locale="en" value="Created"/>
	</resource>
	<resource key="field.reg_usn" >
		<message locale="ko" value="등록자"/>
		<message locale="en" value="Create by "/>
	</resource>
</bundle>

=== bluevlad/Java/HKMCA_2008/WebContent/WEB-INF/maf-resource/order.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE maf-resource PUBLIC "-//UBQ//DTD maf-command config XML V1.0//EN" "resourceBundle.dtd">

<bundle defaultLocale="ko">
    <resource key="ord_cd" >
        <message locale="ko" value="주문코드" />
    </resource>
    <resource key="cpn_use" >
        <message locale="ko" value="쿠폰사용여부" />
    </resource>
    <resource key="coupon_no" >
        <message locale="ko" value="쿠폰번호" />
    </resource>
    <resource key="ord_sta" >
        <message locale="ko" value="주문상태" />
    </resource>
    <resource key="ord_dt" >
        <message locale="ko" value="주문일자" />
    </resource>
    <resource key="ord_det_no" >
        <message locale="ko" value="주문상세코드" />
    </resource>
    <resource key="ord_det_sta" >
        <message locale="ko" value="주문상세상태" />
    </resource>
    <resource key="snd_dt" >
        <message locale="ko" value="발송일" />
    </resource>
    <resource key="total_pay" >
        <message locale="ko" value="주문총액" />
    </resource>
    <resource key="discount" >
        <message locale="ko" value="할인액" />
    </resource>
    <resource key="order_pay" >
        <message locale="ko" value="결재금액" />
    </resource>
    <resource key="qty" >
        <message locale="ko" value="주문수량" />
    </resource>
</bundle>

=== bluevlad/Java/MAF_JDK1.5/WebContent/WEB-INF/maf-resource/table.bas_crs_cd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE maf-resource PUBLIC "-//Miranet//DTD maf-command config XML V1.0//EN" "resourceBundle.dtd">

<bundle defaultLocale="en">
  <resource key="cert_lvl" type="text">
    <message locale="en" value="Certification Level" />
    <message locale="ko" value="인증레벨" />
  </resource>
  <resource key="crs_cd" type="text">
    <message locale="en" value="Course ID" />
    <message locale="ko" value="과정ID" />
  </resource>
  <resource key="crs_nm" type="text">
    <message locale="en" value="Course Name" />
    <message locale="ko" value="과정명" />
  </resource>
  <resource key="crs_short_nm" type="text">
    <message locale="en" value="Abbreviated course name" />
    <message locale="ko" value="과정명약칭" />
  </resource>
  <resource key="ctype" type="text">
    <message locale="en" value="Course Type" />
    <message locale="ko" value="과정유형" />
  </resource>
  <resource key="dlr_cd" type="text">
    <message locale="en" value="Dealer Code" />
    <message locale="ko" value="딜러코드" />
  </resource>
  <resource key="field" type="text">
    <message locale="en" value="Course Classification" />
    <message locale="ko" value="과정구분" />
  </resource>
  <resource key="is_autocerti" type="text">
    <message locale="en" value="Automatic Certification" />
    <message locale="ko" value="자동인증여부" />
  </resource>
  <resource key="isuse" type="text">
    <message locale="en" value="Usage" />
    <message locale="ko" value="사용여부" />
  </resource>
  <resource key="orgn_cd" type="text">
    <message locale="en" value="Organization Code" />
    <message locale="ko" value="조직코드" />
  </resource>
  <resource key="otype" type="text">
    <message locale="en" value="On/Off Type" />
    <message locale="ko" value="온오프구분" />
  </resource>
  <resource key="passcondition" type="text">
    <message locale="en" value="Course completion condition" />
    <message locale="ko" value="수료조건" />
  </resource>
  <resource key="precondition" type="text">
    <message locale="en" value="Course application condition" />
    <message locale="ko" value="선수조건" />
  </resource>
  <resource key="section" type="text">
    <message locale="en" value="Job Domain" />
    <message locale="ko" value="업무영역" />
  </resource>
  <resource key="test_type" type="text">
    <message locale="en" value="Exam Type" />
    <message locale="ko" value="시험유형" />
  </resource>
   <resource key="vc_type" type="text">
    <message locale="en" value="Passenger/Commercial" />
    <message locale="ko" value="승용/상용구분" />
  </resource>
</bundle>

=== bluevlad/Java/MAF_JDK1.7/WebContent/WEB-INF/maf-resource/table.wra_inx_lst.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE maf-resource PUBLIC "-//Miranet//DTD maf-command config XML V1.0//EN" "resourceBundle.dtd">

<bundle defaultLocale="en">
  <resource key="batchupload" type="text">
    <message locale="en" value="File registration - group" />
    <message locale="ko" value="일괄파일등록" />
  </resource>
  <resource key="cencode" type="text">
    <message locale="en" value="-" />
    <message locale="ko" value="중단원 코드" />
  </resource>
  <resource key="cenname" type="text">
    <message locale="en" value="-" />
    <message locale="ko" value="중단원 명" />
  </resource>
  <resource key="cmpcode" type="text">
    <message locale="en" value="Contents" />
    <message locale="ko" value="컨텐츠" />
  </resource>
  <resource key="cnt_height" type="text">
    <message locale="en" value="-" />
    <message locale="ko" value="화면높이" />
  </resource>
  <resource key="cnt_width" type="text">
    <message locale="en" value="-" />
    <message locale="ko" value="화면넓이" />
  </resource>
  <resource key="daecode" type="text">
    <message locale="en" value="Chapter code" />
    <message locale="ko" value="차시코드" />
  </resource>
  <resource key="daename" type="text">
    <message locale="en" value="Chapter name" />
    <message locale="ko" value="차시명" />
  </resource>
  <resource key="dlr_cd" type="text">
    <message locale="en" value="-" />
    <message locale="ko" value="딜러코드" />
  </resource>
  <resource key="excel" type="text">
    <message locale="en" value="Excel file registration" />
    <message locale="ko" value="엑셀파일등록" />
  </resource>
  <resource key="htmcode" type="text">
    <message locale="en" value="Serial number" />
    <message locale="ko" value="일련번호" />
  </resource>
  <resource key="htmname" type="text">
    <message locale="en" value="-" />
    <message locale="ko" value="파일명" />
  </resource> 
  <resource key="htmurl" type="text">
    <message locale="en" value="Contents URL" />
    <message locale="ko" value="컨텐츠URL" />
  </resource>
  <resource key="impdat" type="text">
    <message locale="en" value="Registration date" />
    <message locale="ko" value="등록일" />
  </resource>
  <resource key="isuse" type="text">
    <message locale="en" value="Used" />
    <message locale="ko" value="사용여부" />
  </resource>
  <resource key="lrntime" type="text">
    <message locale="en" value="Minimum training time" />
    <message locale="ko" value="최소학습시간" />
  </resource>
  <resource key="orgn_cd" type="text">
    <message locale="en" value="-" />
    <message locale="ko" value="조직코드(대리점)" />
  </resource>
  <resource key="popup_size" type="text">
    <message locale="en" value="Pop up window size" />
    <message locale="ko" value="팝업창크기" />
  </resource>
  <resource key="review" type="text">
    <message locale="en" value="Preview" />
    <message locale="ko" value="미리보기" />
  </resource>
  <resource key="script.msg1" type="text">
    <message locale="en" value="Please input course code" />
    <message locale="ko" value="☞ 과정코드를 입력하세요." />
  </resource>
  <resource key="script.msg10" type="text">
    <message locale="en" value="Please register files with file type ({0})" />
    <message locale="ko" value="※ 등록할 파일의 확장자는 ({0})로 만들어진 파일을 등록하세요." />
  </resource>
  <resource key="script.msg11" type="text">
    <message locale="en" value="Please select the correct file corresponding to the standard" />
    <message locale="ko" value="☞ 기준에 맞는 정확한 파일을 선택하세요." />
  </resource>
  <resource key="script.msg2" type="text">
    <message locale="en" value="Please input course name" />
    <message locale="ko" value="☞ 과정명을 입력하세요." />
  </resource>
  <resource key="script.msg3" type="text">
    <message locale="en" value="Please select subject" />
    <message locale="ko" value="☞ 과목을 선택하세요." />
  </resource>
  <resource key="script.msg4" type="text">
    <message locale="en" value="-" />
    <message locale="ko" value="☞ 대단원코드를 입력하세요." />
  </resource>
  <resource key="script.msg5" type="text">
    <message locale="en" value="-" />
    <message locale="ko" value="☞ 대단원명을 입력하세요." />
  </resource>
  <resource key="script.msg6" type="text">
    <message locale="en" value="파일을 입력한다?" />
    <message locale="ko" value="☞ 시작HTM파일명은 (htm, 또는 html)로 만들어진 파일을 입력하세요." />
  </resource>
  <resource key="script.msg7" type="text">
    <message locale="en" value="Please input pop up window size" />
    <message locale="ko" value="☞ 팝업윈도의 창 크기를 입력해주세요." />
  </resource>
  <resource key="script.msg8" type="text">
    <message locale="en" value="Please input the full path of registered contents" />
    <message locale="ko" value="☞ 등록된 컨텐츠의 full path를 입력해 주세요." />
  </resource>
  <resource key="script.msg9" type="text">
    <message locale="en" value="Please register files with file type (0) or (1)" />
    <message locale="ko" value="※ 등록할 파일의 확장자는 ({0} 또는 {1})로 만들어진 파일을 등록하세요." />
  </resource>
  <resource key="select_subject" type="text">
    <message locale="en" value="Select subject" />
    <message locale="ko" value="과목선택" />
  </resource>
  <resource key="sjtcode" type="text">
    <message locale="en" value="Subject Code" />
    <message locale="ko" value="과목코드" />
  </resource>
  <resource key="sjtname" type="text">
    <message locale="en" value="Subject Name" />
    <message locale="ko" value="과목명" />
  </resource>
  <resource key="socode" type="text">
    <message locale="en" value="Sub course code" />
    <message locale="ko" value="소단원 코드" />
  </resource>
  <resource key="soname" type="text">
    <message locale="en" value="Sub course name" />
    <message locale="ko" value="소단원 명" />
  </resource>
  <resource key="totpage" type="text">
    <message locale="en" value="Total pages" />
    <message locale="ko" value="총페이지수" />
  </resource>
</bundle>

=== bluevlad/Java/MAF_JDK1.7/WebContent/WEB-INF/maf-resource/table.wlb_lec_chp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE maf-resource PUBLIC "-//Miranet//DTD maf-command config XML V1.0//EN" "resourceBundle.dtd">

<bundle defaultLocale="en">
  <resource key="button" type="text">
    <message locale="en" value="Modify course overview sequence" />
    <message locale="ko" value="강의안 순서변경" />
  </resource>
  <resource key="chp_edat" type="text">
    <message locale="en" value="Course completion date" />
    <message locale="ko" value="강의종료일" />
  </resource>
  <resource key="chp_sdat" type="text">
    <message locale="en" value="Course start date" />
    <message locale="ko" value="강의시작일" />
  </resource>
  <resource key="chpnumb" type="text">
    <message locale="en" value="No" />
    <message locale="ko" value="번호" />
  </resource>
  <resource key="cnt_height" type="text">
    <message locale="en" value="Height" />
    <message locale="ko" value="팝업윈도우 창높이" />
  </resource>
  <resource key="cnt_height1" type="text">
    <message locale="en" value="Height" />
    <message locale="ko" value="높이" />
  </resource>
  <resource key="cnt_width" type="text">
    <message locale="en" value="Width" />
    <message locale="ko" value="팝업윈도우 창넓이" />
  </resource>
  <resource key="cnt_width1" type="text">
    <message locale="en" value="Width" />
    <message locale="ko" value="넓이" />
  </resource>
  <resource key="comments_from_lms" type="text">
    <message locale="en" value="-" />
    <message locale="ko" value="lms 코멘트" />
  </resource>
  <resource key="crs_id" type="text">
    <message locale="en" value="Course Identifier" />
    <message locale="ko" value="course 식별자" />
  </resource>
  <resource key="htmcode" type="text">
    <message locale="en" value="Contents Number" />
    <message locale="ko" value="컨텐츠번호" />
  </resource>
  <resource key="itm_id" type="text">
    <message locale="en" value="-" />
    <message locale="ko" value="item 식별자" />
  </resource>
  <resource key="itm_isvisible" type="text">
    <message locale="en" value="Indication" />
    <message locale="ko" value="표시여부" />
  </resource>
  <resource key="itm_location" type="text">
    <message locale="en" value="Location of meta data" />
    <message locale="ko" value="메타데이타의 위치" />
  </resource>
  <resource key="itm_lvl" type="text">
    <message locale="en" value="-" />
    <message locale="ko" value="계층" />
  </resource>
  <resource key="itm_masteryscore" type="text">
    <message locale="en" value="Passing score" />
    <message locale="ko" value="합격기준점수" />
  </resource>
  <resource key="itm_maxtimeallowed_not_used" type="text">
    <message locale="en" value="Maximum training time possible (maximum allowed study time)" />
    <message locale="ko" value="최대학습허용시간" />
  </resource>  
  <resource key="itm_maxtimeallowed" type="text">
<message locale="en" value="Standard training time (standard study time)" />
    <message locale="ko" value="기준학습시간" />
  </resource>
  <resource key="itm_parameterstring" type="text">
    <message locale="en" value="Parameter value" />
    <message locale="ko" value="파라미터 값" />
  </resource>
  <resource key="itm_pid" type="text">
    <message locale="en" value="High rank item identifier" />
    <message locale="ko" value="item 상위 식별자" />
  </resource>
  <resource key="itm_prerequisites" type="text">
    <message locale="en" value="-" />
    <message locale="ko" value="선수 item들" />
  </resource>
  <resource key="itm_sequence" type="text">
    <message locale="en" value="Chapter" />
    <message locale="ko" value="차시" />
  </resource>
  <resource key="itm_timelimitaction" type="text">
    <message locale="en" value="Events after allowed study time lapse" />
    <message locale="ko" value="학습시간 초과후  발생 이벤트" />
  </resource>
  <resource key="itm_title" type="text">
    <message locale="en" value="Title" />
    <message locale="ko" value="제목" />
  </resource>
  <resource key="itm_type" type="text">
    <message locale="en" value="Type" />
    <message locale="ko" value="유형" />
  </resource>
  <resource key="launch_data" type="text">
    <message locale="en" value="Linked data" />
    <message locale="ko" value="연동데이타" />
  </resource>
  <resource key="leccode" type="text">
    <message locale="en" value="Course code" />
    <message locale="ko" value="강의코드" />
  </resource>
  <resource key="msg1" type="text">
    <message locale="en" value="Please select the contents to register" />
    <message locale="ko" value="☞ 등록할 컨텐츠를 선택해주십시요." />
  </resource>
  <resource key="msg2" type="text">
    <message locale="en" value="무엇이?" />
    <message locale="ko" value="※ 컨텐츠 실제 URL을 입력하지 않으면 목차로만 이용합니다." />
  </resource>
  <resource key="netg_cid" type="text">
    <message locale="en" value="External course ID" />
    <message locale="ko" value="외부과정코스id" />
  </resource>
  <resource key="netg_sub_cid" type="text">
    <message locale="en" value="External course sub ID" />
    <message locale="ko" value="외부과정코스서브id" />
  </resource>
  <resource key="off_date_info" type="text">
    <message locale="en" value="Off line course schedule" />
    <message locale="ko" value="오프라인강의일정" />
  </resource>
  <resource key="off_place" type="text">
    <message locale="en" value="Off line course location" />
    <message locale="ko" value="오프라인강의장소" />
  </resource>
  <resource key="org_id" type="text">
    <message locale="en" value="Organization identifier" />
    <message locale="ko" value="Organization 식별자" />
  </resource>
  <resource key="page_prg" type="text">
    <message locale="en" value="Page progress" />
    <message locale="ko" value="페이지진도" />
  </resource>
  <resource key="place_type" type="text">
    <message locale="en" value="On/Off" />
    <message locale="ko" value="온오프구분" />
  </resource>
  <resource key="popup_size" type="text">
    <message locale="en" value="Study window size" />
    <message locale="ko" value="학습창크기" />
  </resource>
  <resource key="preview" type="text">
    <message locale="en" value="Preview" />
    <message locale="ko" value="미리보기" />
  </resource>
  <resource key="res_id" type="text">
    <message locale="en" value="-" />
    <message locale="ko" value="resource 식별자" />
  </resource>
  <resource key="score_max" type="text">
    <message locale="en" value="Highest score accomplished" />
    <message locale="ko" value="성취최대점수" />
  </resource>
  <resource key="score_min" type="text">
    <message locale="en" value="Lowest score accomplished" />
    <message locale="ko" value="성취최소점수" />
  </resource>
  <resource key="title1" type="text">
    <message locale="en" value="Select course" />
    <message locale="ko" value="코스 선택" />
  </resource>
  <resource key="title10" type="text">
    <message locale="en" value="Select contents" />
    <message locale="ko" value="컨텐츠 선택" />
  </resource>
  <resource key="title11" type="text">
    <message locale="en" value="Delete contents" />
    <message locale="ko" value="컨텐츠 삭제" />
  </resource>
  <resource key="title12" type="text">
    <message locale="en" value="Select contents" />
    <message locale="ko" value="컨텐츠 선택" />
  </resource>
  <resource key="title2" type="text">
    <message locale="en" value="Contents URL" />
    <message locale="ko" value="컨텐츠URL" />
  </resource>
  <resource key="title3" type="text">
    <message locale="en" value="-" />
    <message locale="ko" value="점" />
  </resource>
  <resource key="title4" type="text">
    <message locale="en" value="Course overview level number" />
    <message locale="ko" value="강의안계층번호" />
  </resource>
  <resource key="title5" type="text">
    <message locale="en" value="-" />
    <message locale="ko" value="NETg CourseID 1 / CourseID" />
  </resource>
  <resource key="title6" type="text">
    <message locale="en" value="-" />
    <message locale="ko" value="NETg CourseID 2 / 기관코드" />
  </resource>
  <resource key="title7" type="text">
    <message locale="en" value="Minute" />
    <message locale="ko" value="분" />
  </resource>
  <resource key="title8" type="text">
    <message locale="en" value="Phase" />
    <message locale="ko" value="단계" />
  </resource>
  <resource key="title9" type="text">
    <message locale="en" value="None" />
    <message locale="ko" value="없음" />
  </resource>
  <resource key="totpage" type="text">
    <message locale="en" value="Total number of pages" />
    <message locale="ko" value="총페이지수" />
  </resource>
  <resource key="update_dt" type="text">
    <message locale="en" value="Final update - date" />
    <message locale="ko" value="최종 수정일" />
  </resource>
  <resource key="update_id" type="text">
    <message locale="en" value="Final update - ID" />
    <message locale="ko" value="최종수정id" />
  </resource>
  <resource key="version" type="text">
    <message locale="en" value="Contents version" />
    <message locale="ko" value="컨텐츠버전" />
  </resource>
  <resource key="week" type="text">
    <message locale="en" value="Week" />
    <message locale="ko" value="주" />
  </resource>
</bundle>

=== bluevlad/Java/MAF_JDK1.7/WebContent/WEB-INF/maf-resource/table.bas_subject_cd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE maf-command PUBLIC
         "-//Miranet//DTD maf-command config XML V1.0//EN"
         "resourceBundle.dtd">

<bundle defaultLocale="en">
	<resource key="sjt_cd"> 
		<message locale="ko" value="과목코드"/>
		<message locale="en" value="Subject Code"/>
	</resource>
	<resource key="sbj_type">
		<message locale="ko" value="Type"/>
		<message locale="en" value="Type"/>
	</resource>
	
	<resource key="subject_nm">
		<message locale="en" value="Subject Name"/>
		<message locale="ko" value="과목명"/>
	</resource>
	<resource key="name_eng">
		<message locale="ko" value="영문과목명"/>
		<message locale="en" value="Name_eng"/>
	</resource>
	<resource key="isuse">
		<message locale="ko" value="사용여부"/>
		<message locale="en" value="Isuse"/>
	</resource>
	<resource key="stype">
		<message locale="ko" value="과목유형"/>
		<message locale="en" value="Subject Type"/>
	</resource>
	<resource key="otype">
		<message locale="ko" value="온/오프구분"/>
		<message locale="en" value="On/Off"/>
	</resource>
	<resource key="price">
		<message locale="ko" value="교육비"/>
		<message locale="en" value="Price"/>
	</resource>
	<resource key="term">
		<message locale="ko" value="기간"/>
		<message locale="en" value="Term"/>
	</resource>
	<resource key="outline">
		<message locale="ko" value="과목개요"/>
		<message locale="en" value="Outline"/>
	</resource>
	<resource key="target">
		<message locale="ko" value="수강대상"/>
		<message locale="en" value="Target"/>
	</resource>
	<resource key="precondition">
		<message locale="ko" value="선수조건"/>
		<message locale="en" value="Precondition"/>
	</resource>
	<resource key="contents">
		<message locale="ko" value="교육내용"/>
		<message locale="en" value="Contents"/>
	</resource>
	<resource key="level_type">
		<message locale="ko" value="난이도"/>
		<message locale="en" value="Level"/>
	</resource>
	<resource key="ad_new">
		<message locale="ko" value="신규과정"/>
		<message locale="en" value="Ad_new"/>
	</resource>
	<resource key="ad_recommend">
		<message locale="ko" value="추천과정"/>
		<message locale="en" value="Ad_recommend"/>
	</resource>
	<resource key="section">
		<message locale="ko" value="업무영역"/>
		<message locale="en" value="Job Domain"/>
	</resource>
	<resource key="grade">
		<message locale="ko" value="인증등급"/>
		<message locale="en" value="Grade"/>
	</resource>
	<resource key="field">
		<message locale="ko" value="구분"/>
		<message locale="en" value="Field"/>
	</resource>
	<resource key="cert_lvl">
		<message locale="ko" value="인증레벨"/>
		<message locale="en" value="Cert. Level"/>
	</resource>
	<resource key="test_type">
		<message locale="ko" value="테스트유형"/>
		<message locale="en" value="Test_type"/>
	</resource>
	<resource key="division">
		<message locale="ko" value="소속조직"/>
		<message locale="en" value="Division"/>
	</resource>
	<resource key="orgn_cd">
		<message locale="ko" value="조직코드"/>
		<message locale="en" value="Org. Code"/>
	</resource>
	<resource key="dlr_cd">
		<message locale="ko" value="딜러코드"/>
		<message locale="en" value="Dealer Code"/>
	</resource>
	<resource key="year">
		<message locale="ko" value="Year"/>
		<message locale="en" value="Year"/>
	</resource>
	<resource key="attachment">
		<message locale="ko" value="Attachment"/>
		<message locale="en" value="Attachment"/>
	</resource>
	<resource key="currency">
		<message locale="ko" value="지역 유통화폐단위"/>
		<message locale="en" value="Local Currency"/>
	</resource>
	
	<resource key="mandatory">
		<message locale="ko" value="필수"/>
		<message locale="en" value="Mandatory"/>
	</resource>
	<resource key="optional">
		<message locale="ko" value="선택"/>
		<message locale="en" value="Optional"/>
	</resource>

</bundle>
