=== bluevlad/Java/MAF_JDK1.5/WebContent/WEB-INF/maf-resource/resourceBundle.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
	 mvc conrol Configuration
	 Version : 1.0	(2005.03.30)
	 Author : Kim Sang Joon
-->
<!-- 
	configuration is the root element. 
	template-list : 테프릿 이름과 Block(Template-Info)들 정의 
-->
<!ELEMENT bundle (desctiption | resource)*>
<!ATTLIST bundle
	defaultLocale CDATA #REQUIRED 
	imagePath CDATA #IMPLIED 
	desc 	CDATA #IMPLIED 
>
<!ELEMENT desctiption (#PCDATA)>
<!--
   filename이 정의 되었을경우 imagePath / filename 으로 img 버튼을 만듬 
-->
<!ELEMENT resource (message)*>
<!ATTLIST resource
	key 	ID  #REQUIRED 
	value 	CDATA #IMPLIED 
	type	(text|gif|jpeg) #IMPLIED
	desc 	CDATA #IMPLIED 
	filename CDATA #IMPLIED
	icon CDATA #IMPLIED
>

<!ELEMENT message (#PCDATA)>
<!ATTLIST message
	locale	CDATA  #REQUIRED
	value 	CDATA  #IMPLIED 
	desc 	CDATA #IMPLIED 
	filename CDATA #IMPLIED	
	icon CDATA #IMPLIED
>

=== bluevlad/Java/MAF_JDK1.7/WebContent/WEB-INF/maf-resource/table.bas_record.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE maf-command PUBLIC
         "-//Miranet//DTD maf-command config XML V1.0//EN"
         "resourceBundle.dtd">
<bundle defaultLocale="ko">

	<resource key="target_cd" >
		<message locale="ko" value="목표식별코드" />
		<message locale="en" value="Target_cd" />
	</resource>
	<resource key="grade" >
		<message locale="ko" value="인증구분" />
		<message locale="en" value="Grade" />
	</resource>
	<resource key="section" >
		<message locale="ko" value="업무영역" />
		<message locale="en" value="Section" />
	</resource>
	<resource key="record" >
		<message locale="ko" value="실적" />
		<message locale="en" value="Record" />
	</resource>
	<resource key="record_dt" >
		<message locale="ko" value="실적처리일" />
		<message locale="en" value="Record_dt" />
	</resource>
	<resource key="insert_id" >
		<message locale="ko" value="등록자" />
		<message locale="en" value="Insert_id" />
	</resource>
	<resource key="insert_dt" >
		<message locale="ko" value="등록일" />
		<message locale="en" value="Insert_dt" />
	</resource>
	<resource key="update_id" >
		<message locale="ko" value="수정자" />
		<message locale="en" value="Update_id" />
	</resource>
	<resource key="update_dt" >
		<message locale="ko" value="수정일" />
		<message locale="en" value="Update_dt" />
	</resource>
	
</bundle>

=== bluevlad/Java/HKMCA_2008/WebContent/WEB-INF/maf-resource/table.maf_user.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE maf-command PUBLIC
         "-//Miranet//DTD maf-command config XML V1.0//EN"
         "resourceBundle.dtd">
<bundle defaultLocale="ko">
	<resource key="usn" >
		<message locale="ko" value="회원코드" />
		<message locale="en" value="Userid" />
	</resource>
	<resource key="userid" >
		<message locale="ko" value="사용자 id" />
		<message locale="en" value="User ID" />
	</resource>
	<resource key="passwd" >
		<message locale="ko" value="사용자 암호" />
		<message locale="en" value="Password" />
	</resource>
	<resource key="nm" >
		<message locale="ko" value="이름" />
		<message locale="en" value="Name" />
	</resource>
	<resource key="nick_nm" >
		<message locale="ko" value="별명" />
		<message locale="en" value="Nick name" />
	</resource>
	<resource key="nm_eng" >
		<message locale="ko" value="영문이름" />
		<message locale="en" value="English Name" />
	</resource>
	<resource key="pin" >
		<message locale="en" value="PIN" />
		<message locale="ko" value="주민번호" />
	</resource>
    <resource key="pos_nm" >
        <message locale="en" value="Position" />
        <message locale="ko" value="부서" />
    </resource>
	<resource key="hp" >
		<message locale="ko" value="핸드폰" />
		<message locale="en" value="Mobile" />
	</resource>
	<resource key="tel" >
		<message locale="ko" value="전화번호" />
		<message locale="en" value="Tel." />
	</resource>
	<resource key="fax" >
		<message locale="ko" value="팩스" />
		<message locale="en" value="Fax" />
	</resource>
	<resource key="email" >
		<message locale="ko" value="이메일" />
		<message locale="en" value="Email" />
	</resource>
	<resource key="addr1" >
		<message locale="en" value="Address " />
		<message locale="ko" value="주소앞부분" />
	</resource>
	<resource key="remarks" >
		<message locale="en" value="Etc" />
		<message locale="ko" value="비고" />
	</resource>
	<resource key="addr2" >
		<message locale="en" value="Address " />
		<message locale="ko" value="주소상세(나머지)" />
	</resource>
	<resource key="zip" >
		<message locale="en" value="Post No" />
		<message locale="ko" value="우편번호" />
	</resource>
	<resource key="pos_cd" >
		<message locale="en" value="Post No" />
	</resource>
	<resource key="org_cd" >
		<message locale="en" value="Org ID" />
		<message locale="ko" value="조직코드" />
	</resource>
	<resource key="add" >
		<message locale="ko" value="주소" />
		<message locale="en" value="Address" />
	</resource>
    <resource key="role_id" >
        <message locale="ko" value="사용자코드" />
        <message locale="en" value="Role_id" />
    </resource>
    <resource key="role_name" >
        <message locale="ko" value="권한명" />
        <message locale="en" value="Role_Name" />
    </resource>
    <resource key="is_super" >
        <message locale="ko" value="슈퍼바이저권한" />
        <message locale="en" value="Supervisor" />
    </resource>
    <resource key="is_nologin" >
        <message locale="ko" value="게스트권한" />
        <message locale="en" value="Guest" />
    </resource>
    <resource key="bbs_level" >
        <message locale="ko" value="게시판권한" />
        <message locale="en" value="Board Auth" />
    </resource>
    <resource key="fixed" >
        <message locale="ko" value="시스템고정" />
        <message locale="en" value="Fixed" />
    </resource>
    <resource key="site" >
        <message locale="ko" value="사이트" />
        <message locale="en" value="SITE" />
    </resource>
</bundle>

=== bluevlad/Java/MAF_JDK1.4/WebContent/WEB-INF/maf-resource/table.wse_mail_history.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE maf-command PUBLIC
         "-//Miranet//DTD maf-command config XML V1.0//EN"
         "resourceBundle.dtd">
<bundle defaultLocale="en">

	<resource key="userid" >
		<message locale="ko" value="회원id" />
		<message locale="en" value="Userid" />
	</resource>

	<resource key="send_no" >
		<message locale="ko" value="발송일련번호" />
		<message locale="en" value="Mail Sequence ID" />
	</resource>

	<resource key="send_id" >
		<message locale="ko" value="발송id" />
		<message locale="en" value="Sender ID" />
	</resource>

	<resource key="leccode" >
		<message locale="ko" value="강의코드" />
		<message locale="en" value="Lecture Code" />
	</resource>

	<resource key="user_nm" >
		<message locale="ko" value="회원명" />
		<message locale="en" value="Username" />
	</resource>

	<resource key="email" >
		<message locale="ko" value="이메일" />
		<message locale="en" value="Email" />
	</resource>

	<resource key="result" >
		<message locale="ko" value="전송결과[0:전송성공,  0 미만 값: 전송실패]" />
		<message locale="en" value="Result" />
	</resource>

	<resource key="from_id" >
		<message locale="ko" value="보낸이" />
		<message locale="en" value="Sender" />
	</resource>

	<resource key="send_dt" >
		<message locale="ko" value="보낸일" />
		<message locale="en" value="Sent Date" />
	</resource>

	<resource key="mail_title" >
		<message locale="ko" value="메일제목" />
		<message locale="en" value="Subject" />
	</resource>

	<resource key="mail_text" >
		<message locale="ko" value="메일내용" />
		<message locale="en" value="Content" />
	</resource>

	<resource key="mail_type" >
		<message locale="ko" value="메일형태[a:경고[독촉]/ i:알림메일]" />
		<message locale="en" value="Mail Type" />
	</resource>

	<resource key="update_dt" >
		<message locale="ko" value="최종수정일[수정된 현재일이 등록됨]" />
		<message locale="en" value="Update Date" />
	</resource>

	<resource key="update_id" >
		<message locale="ko" value="최종수정id" />
		<message locale="en" value="Update ID" />
	</resource>

	<resource key="mail_pattern" >
		<message locale="ko" value="메일 내용 유형" />
		<message locale="en" value="Mail Type" />
	</resource>

	<resource key="isread" >
		<message locale="ko" value="읽음 여부(y:읽음, n:안읽음)" />
		<message locale="en" value="Read" />
	</resource>
	
	<resource key="select.wse_mail_history.mail_type.alert" >
		<message locale="ko" value="경고[Alert]메일"/>
		<message locale="en" value="Alert Mail"/>
	</resource>
	<resource key="select.wse_mail_history.mail_type.info" >
		<message locale="ko" value="알림[Information]메일"/>
		<message locale="en" value="Information Mail"/>
	</resource>
	<resource key="select.wse_mail_history.result.ok" >
		<message locale="ko" value="성공"/>
		<message locale="en" value="Success"/>
	</resource>
	<resource key="select.wse_mail_history.result.error1" >
		<message locale="ko" value="메일주소오류"/>
		<message locale="en" value="Invalid Email Address"/>
	</resource>
	<resource key="select.wse_mail_history.result.error2" >
		<message locale="ko" value="전송실패"/>
		<message locale="en" value="Failure"/>
	</resource>
	<resource key="select.wse_mail_history.result.error3" >
		<message locale="ko" value="실패[기타오류]"/>
		<message locale="en" value="Failure (ETC)"/>
	</resource>
	<resource key="select.wse_mail_history.result.error" >
		<message locale="ko" value="실패"/>
		<message locale="en" value="Failure"/>
	</resource>
	
</bundle>

=== bluevlad/Java/HKMCA_2008/WebContent/WEB-INF/maf-resource/table.exm_bnk.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE maf-command PUBLIC
         "-//UBQ//DTD maf-command config XML V1.0//EN"
         "resourceBundle.dtd">
<bundle defaultLocale="ko">
    <resource key="queid" >
        <message locale="ko" value="문제 번호" />
    </resource>
    <resource key="queowner" >
        <message locale="ko" value="소유자" />
    </resource>
    <resource key="sjt_cd" >
        <message locale="ko" value="과목명" />
    </resource>
    <resource key="quetitle" >
        <message locale="ko" value="질문" />
    </resource>
    <resource key="quetext" >
        <message locale="ko" value="문제지문" />
    </resource>
    <resource key="queimag" >
        <message locale="ko" value="문제이미지" />
    </resource>
    <resource key="queviw1" >
        <message locale="ko" value="보기1" />
    </resource>
    <resource key="queviw2" >
        <message locale="ko" value="보기2" />
    </resource>
    <resource key="queviw3" >
        <message locale="ko" value="보기3" />
    </resource>
    <resource key="queviw4" >
        <message locale="ko" value="보기4" />
    </resource>
    <resource key="queviw5" >
        <message locale="ko" value="보기5" />
    </resource>
    <resource key="queviw6" >
        <message locale="ko" value="보기6" />
    </resource>
    <resource key="queviw7" >
        <message locale="ko" value="보기7" />
    </resource>
    <resource key="queviw8" >
        <message locale="ko" value="보기8" />
    </resource>
    <resource key="queviw9" >
        <message locale="ko" value="보기9" />
    </resource>
    <resource key="queviw10" >
        <message locale="ko" value="보기10" />
    </resource>
    <resource key="quecount" >
        <message locale="ko" value="보기수" />
    </resource>
    <resource key="quedesc" >
        <message locale="ko" value="해설" />
    </resource>
    <resource key="quedescimg" >
        <message locale="ko" value="해설이미지" />
    </resource>
    <resource key="queansw" >
        <message locale="ko" value="정답 " />
    </resource>
    <resource key="quescore" >
        <message locale="ko" value="배점" />
    </resource>
    <resource key="quetype" >
        <message locale="ko" value="유형" />
    </resource>
    <resource key="quelevel" >
        <message locale="ko" value="난이도" />
    </resource>
</bundle>

=== bluevlad/Java/MAF_JDK1.7/WebContent/WEB-INF/maf-resource/table.bas_org_photo.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE maf-command PUBLIC
         "-//Miranet//DTD maf-command config XML V1.0//EN"
         "resourceBundle.dtd">
<bundle defaultLocale="en">
	<resource key="org_cd">
		<message locale="ko" value="조직 코드" />
		<message locale="en" value="Org Code" />
	</resource>
	<resource key="photo_id">
		<message locale="ko" value="조직내 순번" />
		<message locale="en" value="Photo ID" />
	</resource>
	<resource key="photo_comment">
		<message locale="ko" value="Comment" />
		<message locale="en" value="Comment" />
	</resource>
	<resource key="file_name">
		<message locale="ko" value="저장된 파일명" />
		<message locale="en" value="Saved Filename" />
	</resource>
	<resource key="reg_usn">
		<message locale="ko" value="등록자 usn" />
		<message locale="en" value="Writer" />
	</resource>
	<resource key="reg_dt">
		<message locale="ko" value="등록일" />
		<message locale="en" value="Reg. Date" />
	</resource>
	<resource key="org_filename">
		<message locale="ko" value="원본파일명" />
		<message locale="en" value="Original Filename" />
	</resource>
	<resource key="update_usn">
		<message locale="ko" value="최종 수정자" />
		<message locale="en" value="Update User ID" />
	</resource>
	<resource key="update_dt">
		<message locale="ko" value="최종수정일" />
		<message locale="en" value="Update Date" />
	</resource>
</bundle>

=== bluevlad/Java/MAF_JDK1.5/WebContent/WEB-INF/maf-resource/board.message.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE maf-resource PUBLIC "-//Miranet//DTD maf-command config XML V1.0//EN" "resourceBundle.dtd">

<bundle defaultLocale="en">
  <resource key="comment.added" type="text">
    <message locale="en" value="Comment added" />
    <message locale="ko" value="코멘트가 등록되었습니다" />
  </resource>
  <resource key="comment.deleted" type="text">
    <message locale="en" value="Comment deleted" />
    <message locale="ko" value="코멘트가 등록되었습니다" />
  </resource>
    <resource key="delete.ok" type="text">
    <message locale="en" value="record(s) deleted." />
    <message locale="ko" value="개의 레코드가 정상적으로 Delete 되었습니다." />
  </resource>
  <resource key="delete.fail" type="text">
    <message locale="en" value="Deletion could not be completed." />
    <message locale="ko" value="삭제하지 못하였습니다." />
  </resource>
  <resource key="insert.ok" type="text">
    <message locale="en" value="Registered." />
    <message locale="ko" value="등록되었습니다." />
  </resource>
    <resource key="insert.fail" type="text">
    <message locale="en" value="Registration could not be completed." />
    <message locale="ko" value="등록하지 못하였습니다." />
  </resource>
  <resource key="update.ok" type="text">
    <message locale="en" value="Modified." />
    <message locale="ko" value="수정되었습니다." />
  </resource>  
  
  <resource key="update.fail" type="text">
    <message locale="en" value="could not be modified." />
    <message locale="ko" value="수정하지 못하였습니다." />
  </resource>
  <resource key="invalid.op" type="text">
    <message locale="en" value="Invalid Operation" />
    <message locale="ko" value="잘못된 요청입니다" />
  </resource> 
</bundle>

=== bluevlad/Java/HKMCA_2008/WebContent/WEB-INF/maf-resource/table.maf_lang_iso639_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE maf-command PUBLIC
         "-//UBQ//DTD maf-command config XML V1.0//EN"
         "resourceBundle.dtd">
<bundle defaultLocale="en">
	<resource key="code"  >
		<message locale="ko" value="코드"/>
		<message locale="en" value="Code"/>
	</resource>
	<resource key="code2"  >
		<message locale="ko" value="코드2"/>
		<message locale="en" value="Code2"/>
	</resource>
	<resource key="allnames"  >
		<message locale="ko" value="모든이름 "/>
		<message locale="en" value="Allnames"/>
	</resource>
	<resource key="active_yn"  >
		<message locale="ko" value="사용여부"/>
		<message locale="en" value="Active(Y/N)"/>
	</resource>
	<resource key="local_name"  >
		<message locale="ko" value="지역명"/>
		<message locale="en" value="Local_name"/>
	</resource>

</bundle>

=== bluevlad/Java/MAF_JDK1.4/WebContent/WEB-INF/maf-resource/table.survey_bank.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE maf-resource PUBLIC "-//Miranet//DTD maf-command config XML V1.0//EN" "resourceBundle.dtd">

<bundle defaultLocale="ko">
  <resource key="label.quecount" type="text">
    <message locale="en" value="{0} question" />
    <message locale="ko" value="{0} 문항" />
  </resource>
  <resource key="quedesc" type="text">
    <message locale="en" value="Explanation" />
    <message locale="ko" value="해설" />
  </resource>
  <resource key="queid" type="text">
    <message locale="en" value="Question Number" />
    <message locale="ko" value="설문 번호" />
  </resource>
  <resource key="quecount" type="text">
    <message locale="en" value="Number of choices" />
    <message locale="ko" value="보기수" />
  </resource>
  <resource key="quetitle" type="text">
    <message locale="en" value="Question" />
    <message locale="ko" value="질문" />
  </resource>
  <resource key="quetype" type="text">
    <message locale="en" value="Type" />
    <message locale="ko" value="유형" />
  </resource>
  <resource key="queviw" type="text">
    <message locale="en" value="Answer" />
    <message locale="ko" value="Answer" />
  </resource>
  <resource key="qweowner" type="text">
    <message locale="en" value="Question Possessor" />
    <message locale="ko" value="문제소유자" />
  </resource>
  <resource key="title" type="text">
    <message locale="en" value="Questionare" />
    <message locale="ko" value="설문제목" />
  </resource>
</bundle>
