=== bluevlad/Java/MAF_JDK1.5/WebContent/WEB-INF/maf-resource/resourceBundle.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
	 mvc conrol Configuration
	 Version : 1.0	(2005.03.30)
	 Author : Kim Sang Joon
-->
<!-- 
	configuration is the root element. 
	template-list : 테프릿 이름과 Block(Template-Info)들 정의 
-->
<!ELEMENT bundle (desctiption | resource)*>
<!ATTLIST bundle
	defaultLocale CDATA #REQUIRED 
	imagePath CDATA #IMPLIED 
	desc 	CDATA #IMPLIED 
>
<!ELEMENT desctiption (#PCDATA)>
<!--
   filename이 정의 되었을경우 imagePath / filename 으로 img 버튼을 만듬 
-->
<!ELEMENT resource (message)*>
<!ATTLIST resource
	key 	ID  #REQUIRED 
	value 	CDATA #IMPLIED 
	type	(text|gif|jpeg) #IMPLIED
	desc 	CDATA #IMPLIED 
	filename CDATA #IMPLIED
	icon CDATA #IMPLIED
>

<!ELEMENT message (#PCDATA)>
<!ATTLIST message
	locale	CDATA  #REQUIRED
	value 	CDATA  #IMPLIED 
	desc 	CDATA #IMPLIED 
	filename CDATA #IMPLIED	
	icon CDATA #IMPLIED
>

=== bluevlad/Java/HKMCA_2008/WebContent/WEB-INF/maf-resource/table.maf_menu.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE maf-command PUBLIC
         "-//UBQ//DTD maf-command config XML V1.0//EN"
         "resourceBundle.dtd">
<bundle defaultLocale="ko">
    <resource key="pgid" >
        <message locale="ko" value="메뉴코드" />
        <message locale="en" value="Menu Code" />
    </resource>
    <resource key="title" >
        <message locale="ko" value="메뉴명" />
        <message locale="en" value="Menu Title" />
    </resource>
    <resource key="page" >
        <message locale="ko" value="메뉴주소" />
        <message locale="en" value="URL" />
    </resource>
    <resource key="seq" >
        <message locale="ko" value="순번" />
        <message locale="en" value="Seq." />
    </resource>
    <resource key="pnodeid" >
        <message locale="ko" value="상위메뉴" />
        <message locale="en" value="Upper menu" />
    </resource>
    <resource key="isuse" >
        <message locale="ko" value="사용여부" />
        <message locale="en" value="Use" />
    </resource>
    <resource key="target" >
        <message locale="ko" value="프레임타겟" />
        <message locale="en" value="Target" />
    </resource>
    <resource key="dir" >
        <message locale="ko" value="폴더명" />
        <message locale="en" value="Folder" />
    </resource>
    <resource key="islink" >
        <message locale="ko" value="링크여부" />
        <message locale="en" value="Link" />
    </resource>
    <resource key="usn" >
        <message locale="ko" value="사용자" />
        <message locale="en" value="USN" />
    </resource>
    <resource key="upt_dt" >
        <message locale="ko" value="등록일" />
        <message locale="en" value="Update Date" />
    </resource>
    <resource key="layout" >
        <message locale="ko" value="템플릿" />
        <message locale="en" value="Layout" />
    </resource>
    <resource key="is_lmenu" >
        <message locale="ko" value="좌측메뉴여부" />
        <message locale="en" value="Left Menu" />
    </resource>
    <resource key="is_tmenu" >
        <message locale="ko" value="상위메뉴여부" />
        <message locale="en" value="Top Menu" />
    </resource>
    <resource key="short_desc" >
        <message locale="ko" value="간략설명" />
        <message locale="en" value="DESC" />
    </resource>
    <resource key="session_chk" >
        <message locale="ko" value="세션체크여부" />
        <message locale="en" value="SEssion Check" />
    </resource>
    <resource key="title_en" >
        <message locale="ko" value="영문메뉴명" />
        <message locale="en" value="English Title" />
    </resource>
    <resource key="style" >
        <message locale="ko" value="디자인" />
        <message locale="en" value="Style" />
    </resource>
    <resource key="isservlet" >
        <message locale="ko" value="서브릿여부" />
        <message locale="en" value="Servlet" />
    </resource>
    <resource key="is_sitemap" >
        <message locale="ko" value="사이트맵등록여부" />
        <message locale="en" value="Sitemap" />
    </resource>
    <resource key="admin_usn" >
        <message locale="ko" value="메뉴관리자" />
        <message locale="en" value="Administrator" />
    </resource>
    <resource key="contact_email" >
        <message locale="ko" value="담당자이메일" />
        <message locale="en" value="email" />
    </resource>
    <resource key="contact" >
        <message locale="ko" value="담당자" />
        <message locale="en" value="Contact" />
    </resource>
    <resource key="help_file" >
        <message locale="ko" value="헬프파일명" />
        <message locale="en" value="Help File" />
    </resource>
    <resource key="menu_desc" >
        <message locale="ko" value="메뉴설명" />
        <message locale="en" value="Menu Desc." />
    </resource>
    <resource key="p_cnt" >
        <message locale="ko" value="" />
    </resource>
    <resource key="p_cnt_ok" >
        <message locale="ko" value="" />
    </resource>
    <resource key="upt_id" >
        <message locale="ko" value="등록자" />
    </resource>
    <resource key="p_start_dt" >
        <message locale="ko" value="등록일" />
    </resource>
    <resource key="p_end_dt" >
        <message locale="ko" value="사용기한" />
    </resource>
    <resource key="messagekey" >
        <message locale="ko" value="메세지코드" />
        <message locale="en" value="Message Key" />
    </resource>
</bundle>

=== bluevlad/Java/HKMCA_2008/WebContent/WEB-INF/maf-resource/common.message.board.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE maf-resource PUBLIC "-//UBQ//DTD maf-command config XML V1.0//EN" "resourceBundle.dtd">

<bundle defaultLocale="en">
    <resource key="insert.ok" type="text">
        <message locale="en" value="Registered." />
        <message locale="ko" value="등록되었습니다." />
    </resource>
    <resource key="insert.fail" type="text">
        <message locale="en" value="Registration could not be completed." />
        <message locale="ko" value="등록중 오류가 발생하였습니다." />
    </resource>
    <resource key="update.ok" type="text">
        <message locale="en" value="Modified." />
        <message locale="ko" value="수정되었습니다." />
    </resource>  
    <resource key="update.fail" type="text">
        <message locale="en" value="could not be modified." />
        <message locale="ko" value="수정중 오류가 발생했습니다." />
    </resource>
    <resource key="delete.ok" type="text">
        <message locale="en" value="record(s) deleted." />
        <message locale="ko" value="정상적으로  삭제되었습니다." />
    </resource>
    <resource key="delete.fail" type="text">
        <message locale="en" value="Deletion could not be completed." />
        <message locale="ko" value="삭제중 오류가 발생하였습니다." />
    </resource>
    <resource key="invalid.op" type="text">
        <message locale="en" value="Invalid Operation" />
        <message locale="ko" value="잘못된 요청입니다" />
    </resource> 
    <resource key="list.error" type="text">
        <message locale="ko" value="게시판 목록 가져오는중 오류가 발생하였습니다." />
    </resource>
    <resource key="message.reply_fail" type="text">
        <message locale="en" value="Answer/Reply/Feedback has not been registered." />
        <message locale="ko" value="답변이 등록되지 못하였습니다." />
    </resource>
    <resource key="message.reply_ok" type="text">
        <message locale="en" value="Answer/Reply/Feedback has been registered." />
        <message locale="ko" value="답변이 등록되었습니다." />
    </resource>
    <resource key="comment.added" type="text">
        <message locale="en" value="Comment added" />
        <message locale="ko" value="코멘트가 등록되었습니다" />
    </resource>
    <resource key="comment.deleted" type="text">
        <message locale="en" value="Comment deleted" />
        <message locale="ko" value="코멘트가 삭제되었습니다" />
    </resource>
</bundle>

=== bluevlad/Java/HKMCA_2008/WebContent/WEB-INF/maf-resource/common.scripts.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE maf-resource PUBLIC "-//UBQ//DTD maf-command config XML V1.0//EN" "resourceBundle.dtd">

<bundle defaultLocale="ko">
    <resource key="zipcode.addr.input" type="text">
        <message locale="ko" value="☞ 찾고자 하는 주소를 입력하세요." />
        <message locale="en" value="☞ 찾고자 하는 주소를 입력하세요." />
    </resource>
    <resource key="zipcode.form.notfound" type="text">
        <message locale="ko" value="입력폼이 정의되지 않았습니다." />
        <message locale="en" value="i can't found form name" />
    </resource>
    <resource key="zipcode.addr2.input" type="text">
        <message locale="ko" value="상세주소를 입력해 주십시요." />
        <message locale="en" value="상세주소를 입력해 주십시요." />
    </resource>
    <resource key="iduse.input" type="text">
        <message locale="ko" value="☞ 원하는 아이디를 입력하세요." />
    </resource>
    <resource key="alert.delete" type="text">
        <message locale="ko" value="☞ 해당 정보들이 모두 삭제됩니다. 그래도 삭제하시겠습니까?" />
        <message locale="en" value="All selected information will be deleted. Do you wish to continue?" />
    </resource>
    <resource key="alert.save" type="text">
        <message locale="ko" value="☞ 해당 정보들을 저장하시겠습니까?" />
        <message locale="en" value="Do you wish to Save?" />
    </resource>
    <resource key="menu.add" type="text">
        <message locale="ko" value="☞ 하위메뉴를 작성하시겠습니까?" />
    </resource>
	<resource key="lb.lec_chp.script.msg1" type="text">
        <message locale="ko" value="☞ 강의컨텐츠 표준을 선택하세요." />
	    <message locale="en" value="Please select the course contents standard." />
	</resource>
	<resource key="wla_rat_mst.msg1" type="text">
        <message locale="ko" value="☞ 평가비율의 합은 100%가 되도록 다시 조정해주십시요." />
	    <message locale="en" value="Please adjust each grading rate for the total sum to 100%." />
	</resource>
	<resource key="only.number" type="text">
        <message locale="ko" value="☞ 숫자로만 입력해야 합니다." />
	    <message locale="en" value="Please input only with numbers." />
	</resource>
	<resource key="alert.sel0" type="text">
        <message locale="ko" value="☞ 조건을 선택하십시요." />
	    <message locale="en" value="Please select the condition." />
	</resource>
	<resource key="alert.score.limit.fail" type="text">
        <message locale="ko" value="점수는 0~100 사이의 숫자로 입력하세요." />
	    <message locale="en" value="Please input the scores using numbers between 0~100." />
	</resource>
    <resource key="alert.add" type="text">
        <message locale="ko" value="등록하시겠습니까?" />
        <message locale="en" value="Do you wish to register?" />
    </resource>
    <resource key="alert.add.info" type="text">
        <message locale="ko" value="등록할 항목을 선택하십시오." />
        <message locale="en" value="Please select the item(s) to register." />
    </resource>
    <resource key="alert.copy" type="text">
        <message locale="ko" value="해당항목을 복사하시겠습니까?" />
        <message locale="en" value="Do you wish to copy the selected item?" />
    </resource>
    <resource key="alert.desc" type="text">
        <message locale="ko" value="내용을 입력하세요." />
        <message locale="en" value="Pelase input content." />
    </resource>
    <resource key="alert.email" type="text">
        <message locale="ko" value="☞ email형식이 아닙니다. email형식에 맞게 입력하십시요." />
        <message locale="en" value="&lt;? E-mail form이 뭐죠?&gt; Form is invalid. Please input in e-mail form." />
    </resource>
    <resource key="alert.file" type="text">
        <message locale="ko" value="파일명은 공백없이 영문과 _ 으로 구성됩니다." />
        <message locale="en" value="The file name should be comprised of alphabets and underscore(_) without any blank spaces." />
    </resource>
    <resource key="alert.info1" type="text">
        <message locale="ko" value="☞ 삭제할 항목을 선택하십시오." />
        <message locale="en" value="Please select the item(s) to delete." />
    </resource>
    <resource key="alert.info2" type="text">
        <message locale="ko" value="☞ 선택한 항목을 삭제하겠습니까?" />
        <message locale="en" value="Do you wish to deleted the selected item(s)?" />
    </resource>
    <resource key="alert.member.msg3" type="text">
        <message locale="ko" value="☞ ID를 입력해주세요." />
        <message locale="en" value="Please input ID." />
    </resource>
    <resource key="alert.member.msg4" type="text">
        <message locale="ko" value="☞ 이름을 입력해주세요." />
        <message locale="en" value="Please input the name." />
    </resource>
    <resource key="alert.only.alphanum" type="text">
        <message locale="ko" value="☞ 영문자, 숫자만 사용하여 입력하십시요." />
        <message locale="en" value="Please use alphabet letter and numbers only." />
    </resource>
    <resource key="alert.only.alphanumdash" type="text">
        <message locale="ko" value="☞ 영문자, 숫자,대시(_)만 사용하여 입력하십시요." />
        <message locale="en" value="Please use alphabet letter, numbers and underscores only." />
    </resource>
    <resource key="alert.only.number" type="text">
        <message locale="ko" value="☞ 숫자[0~9]만 사용하여 입력하십시요." />
        <message locale="en" value="Please use single digit numbers only (0~9)." />
    </resource>
    <resource key="alert.percent.limit.fail" type="text">
        <message locale="ko" value="평가비율은 0~100 사이의 숫자로 입력하세요." />
        <message locale="en" value="Please input the grading rate using numbers between 0~100." />
    </resource>
    <resource key="alert.post" type="text">
        <message locale="ko" value="☞ 주소를 입력해주세요." />
        <message locale="en" value="Please input the address." />
    </resource>
    <resource key="classroom.right.button.not.use" type="text">
        <message locale="ko" value="☞ 마우스 오른쪽 버튼을 사용할 수 없습니다." />
        <message locale="en" value="The right mouse button cannot be used." />
    </resource>
    <resource key="mail.msg1" type="text">
        <message locale="ko" value="☞ 보내는사람 항목에 메일주소를 입력해주세요." />
        <message locale="en" value="Please input the mail address in the sender column." />
    </resource>
    <resource key="mail.msg2" type="text">
        <message locale="ko" value="☞ 받는사람 항목에 메일주소를 입력해주세요." />
        <message locale="en" value="Please input the mail address in the receipient column." />
    </resource>
    <resource key="mail.msg3" type="text">
        <message locale="en" value="Please input the mail title." />
        <message locale="ko" value="☞ 메일제목을 입력해 주세요." />
    </resource>
    <resource key="score.rate.100" type="text">
        <message locale="ko" value="평가비율의 합을 100으로 입력하세요." />
        <message locale="en" value="Please input the total grading rate sum as 100." />
    </resource>
	<resource key="alert.not.select" type="text">
        <message locale="ko" value="☞ 대상을 선택하십시오." />
	    <message locale="en" value="Please select item." />
	</resource>
	<resource key="report.marking.notfound" type="text">
        <message locale="ko" value="검색된 학습자가 없습니다." />
	    <message locale="en" value="No trainee found." />
	</resource>
	<resource key="report.marking.notselect" type="text">
        <message locale="ko" value="선택된 학습자가 없습니다." />
	    <message locale="en" value="Please select trainee." />
	</resource>
	<resource key="alert.login" type="text">
        <message locale="ko" value="먼저 로그인하여 주십시오." />
	    <message locale="en" value="Please log-in." />
	</resource>
	<resource key="req.dup" type="text">
        <message locale="ko" value="이미 수강한 과목입니다." />
	</resource>
	<resource key="confirm.apply" type="text">
        <message locale="ko" value="해당 과정을 수강신청 하시겠습니까?" />
	    <message locale="en" value="Do you wish to the register the selected course?" />
	</resource>
    <resource key="pager.delete" type="text">
        <message locale="ko" value="쪽지를 삭제 하시겠습니까?" />
    </resource>
    <resource key="auction.bid_price.not" type="text">
        <message locale="ko" value="입찰금액이 최소입찰 가능금액보다 낮습니다. 다시 입찰해주세요." />
    </resource>
    <resource key="auction.bid.buy_price.ok" type="text">
        <message locale="ko" value="즉시구매가로 입찰하시겠습니까?" />
    </resource>
</bundle>

=== bluevlad/Java/HKMCA_2008/WebContent/WEB-INF/maf-resource/table.wlc_fnl_grd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE maf-resource PUBLIC "-//UBQ//DTD maf-command config XML V1.0//EN" "resourceBundle.dtd">

<bundle defaultLocale="ko">
	<resource key="final_score" type="text">
	    <message locale="ko" value="최종점수" />
	    <message locale="en" value="Final score (grade)" />
	</resource>
	<resource key="tot_score" type="text">
	    <message locale="ko" value="총점" />
	    <message locale="en" value="Total score" />
	</resource>
	<resource key="grad" type="text">
	    <message locale="ko" value="학점" />
	    <message locale="en" value="Grade" />
	</resource>
	<resource key="score1" type="text">
	    <message locale="ko" value="시간진도점수" />
	    <message locale="en" value="Time progress score" />
	</resource>
	<resource key="score2" type="text">
	    <message locale="ko" value="페이지진도점수" />
	    <message locale="en" value="Page progress score" />
	</resource>
	<resource key="score3" type="text">
	    <message locale="ko" value="시험점수" />
	    <message locale="en" value="Exam score" />
	</resource>
	<resource key="score4" type="text">
	    <message locale="ko" value="과제점수" />
	    <message locale="en" value="Homework score" />
	</resource>
	<resource key="score5" type="text">
	    <message locale="ko" value="팀프로젝트점수" />
	    <message locale="en" value="Team project score" />
	</resource>
	<resource key="score6" type="text">
	    <message locale="ko" value="토론실점수" />
	    <message locale="en" value="Discussion score" />
	</resource>
	<resource key="score7" type="text">
	    <message locale="ko" value="학습참여점수" />
	    <message locale="en" value="Training participation score" />
	</resource>
	<resource key="score8" type="text">
	    <message locale="ko" value="오프라인점수" />
	    <message locale="en" value="Off line score" />
	</resource>
	<resource key="score9" type="text">
	    <message locale="ko" value="기타점수" />
	    <message locale="en" value="Other scores" />
	</resource>
	<resource key="score10" type="text">
	    <message locale="ko" value="추가점수" />
	    <message locale="en" value="Additional score" />
	</resource>
    <resource key="appscore" type="text">
        <message locale="ko" value="추가점수" />
        <message locale="en" value="Additional score" />
    </resource>
    <resource key="att_score" type="text">
        <message locale="ko" value="출석 점수" />
        <message locale="en" value="Attend score" />
    </resource>
    <resource key="att_cnt" type="text">
        <message locale="ko" value="출석 일수" />
        <message locale="en" value="Attend Count" />
    </resource>
	<resource key="tot_cnt" type="text">
		<message locale="en" value="Number of gradings" />
		<message locale="ko" value="채점횟수" />
	</resource>
	<resource key="prfid" type="text">
		<message locale="en" value="Grader" />
		<message locale="ko" value="채점자" />
	</resource>
</bundle>

=== bluevlad/Java/MAF_JDK1.7/WebContent/WEB-INF/maf-resource/common.target.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE maf-command PUBLIC
         "-//Miranet//DTD maf-command config XML V1.0//EN"
         "resourceBundle.dtd">
<bundle defaultLocale="en">

	<resource key="certi.deal" >
		<message locale="ko" value="Dealer(code)"/>
		<message locale="en" value="Dealer(code)"/>
	</resource>
	<resource key="certi.certi" >
		<message locale="ko" value="Certification"/>
		<message locale="en" value="Certification"/>
	</resource>
	<resource key="certi.pre" >
		<message locale="ko" value="Present Status"/>
		<message locale="en" value="Present Status"/>
	</resource>
	<resource key="certi.tar" >
		<message locale="ko" value="Target"/>
		<message locale="en" value="Target"/>
	</resource>
	<resource key="certi.st" >
		<message locale="ko" value="Status/Target"/>
		<message locale="en" value="Status/Target"/>
	</resource>
	<resource key="certi.tpr" >
		<message locale="ko" value="Total Possession rate"/>
		<message locale="en" value="Total Possession rate"/>
	</resource>
	<resource key="certi.pos" >
		<message locale="ko" value="Possession"/>
		<message locale="en" value="Possession"/>
	</resource>
	<resource key="certi.rate" >
		<message locale="ko" value="Rate"/>
		<message locale="en" value="Rate"/>
	</resource>
	<resource key="certi.in" >
		<message locale="ko" value="Increase"/>
		<message locale="en" value="Increase"/>
	</resource>
	<resource key="certi.sta" >
		<message locale="ko" value="Status"/>
		<message locale="en" value="Status"/>
	</resource>
	<resource key="certi.tot" >
		<message locale="ko" value="Total"/>
		<message locale="en" value="Total"/>
	</resource>
	<resource key="certi.sm" >
		<message locale="ko" value="Sales Manager"/>
		<message locale="en" value="Sales Manager"/>
	</resource>
	<resource key="certi.parts" >
		<message locale="ko" value="Parts"/>
		<message locale="en" value="Parts"/>
	</resource>
	<resource key="certi.an" >
		<message locale="ko" value="Apply No"/>
		<message locale="en" value="Apply No"/>
	</resource>
	<resource key="certi.pp" >
		<message locale="ko" value="Pass No of person"/>
		<message locale="en" value="Pass No of person"/>
	</resource>
	<resource key="certi.pr" >
		<message locale="ko" value="Pass rate"/>
		<message locale="en" value="Pass rate"/>
	</resource>
	<resource key="certi.pcn" >
		<message locale="ko" value="Present Certified No"/>
		<message locale="en" value="Present Certified No"/>
	</resource>
	<resource key="certi.icn" >
		<message locale="ko" value="Increase Certified No"/>
		<message locale="en" value="Increase Certified No"/>
	</resource>
	<resource key="certi.ir" >
		<message locale="ko" value="Increase rate"/>
		<message locale="en" value="Increase rate"/>
	</resource>
	<resource key="certi.non" >
		<message locale="ko" value="Non"/>
		<message locale="en" value="Non"/>
	</resource>
	<resource key="certi.cnt" >
		<message locale="ko" value="Count"/>
		<message locale="en" value="Count"/>
	</resource>
	<resource key="certi.dif" >
		<message locale="ko" value="Difference"/>
		<message locale="en" value="Difference"/>
	</resource>

	<resource key="lecture.leccnt" >
		<message locale="ko" value="개설강의수"/>
		<message locale="en" value="No of Lecture"/>
	</resource>
	<resource key="lecture.capacity" >
		<message locale="ko" value="정원"/>
		<message locale="en" value="Capacity"/>
	</resource>
	<resource key="lecture.trainees" >
		<message locale="ko" value="수강대상자"/>
		<message locale="en" value="No of Trainees"/>
	</resource>
	<resource key="lecture.req" >
		<message locale="ko" value="수강인원"/>
		<message locale="en" value="No of Request"/>
	</resource>
	<resource key="lecture.rate_req" >
		<message locale="ko" value="신청비율"/>
		<message locale="en" value="Rate of Request"/>
	</resource>
	<resource key="lecture.complete" >
		<message locale="ko" value="수료인원"/>
		<message locale="en" value="No of Complete"/>
	</resource>
	<resource key="lecture.rate_com" >
		<message locale="ko" value="수료비율"/>
		<message locale="en" value="Rate of Complete"/>
	</resource>

</bundle>

=== bluevlad/Java/HKMCA_2008/WebContent/WEB-INF/maf-resource/table.wlc_lec_chp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE maf-resource PUBLIC "-//UBQ//DTD maf-command config XML V1.0//EN" "resourceBundle.dtd">

<bundle defaultLocale="ko">
    <resource key="itm_id" >
        <message locale="ko" value="강의안코드" />
    </resource>
    <resource key="launch_data" >
        <message locale="ko" value="컨텐츠화일" />
    </resource>
    <resource key="itm_title" >
        <message locale="ko" value="제목" />
    </resource>
    <resource key="itm_prerequisites" >
        <message locale="ko" value="선수강의안" />
    </resource>
    <resource key="itm_type" >
        <message locale="ko" value="강의안유형(on:온라인컨텐츠,of:오프라인수업)" />
    </resource>
    <resource key="itm_maxtimeallowed" >
        <message locale="ko" value="기준학습시간" />
    </resource>
    <resource key="itm_sequence" >
        <message locale="ko" value="강의안순서" />
    </resource>
    <resource key="itm_lvl" >
        <message locale="ko" value="계층순서" />
    </resource>
    <resource key="itm_pid" >
        <message locale="ko" value="강의안 상위코드" />
    </resource>
    <resource key="week" >
        <message locale="ko" value="주" />
    </resource>
    <resource key="chpnumb" >
        <message locale="en" value="No" />
        <message locale="ko" value="차시" />
    </resource>
    <resource key="htmcode" >
        <message locale="en" value="Contents Number" />
        <message locale="ko" value="컨텐츠코드" />
    </resource>
    <resource key="totpage" >
        <message locale="ko" value="총페이지수" />
    </resource>
    <resource key="cnt_size" >
        <message locale="ko" value="화면사이즈" />
    </resource>
    <resource key="cnt_width" >
        <message locale="en" value="Width" />
        <message locale="ko" value="화면넓이" />
    </resource>
    <resource key="cnt_height" >
        <message locale="en" value="Height" />
        <message locale="ko" value="화면높이" />
    </resource>
    <resource key="chp_sdat" >
        <message locale="en" value="Course start date" />
        <message locale="ko" value="강의시작일" />
    </resource>
    <resource key="chp_edat" >
        <message locale="en" value="Course completion date" />
        <message locale="ko" value="강의종료일" />
    </resource>
    <resource key="upt_dt" >
        <message locale="ko" value="수정일" />
    </resource>
    <resource key="upt_id" >
        <message locale="ko" value="수정자" />
    </resource>
    <resource key="lec_cd" >
        <message locale="ko" value="개설과목코드" />
    </resource>
</bundle>

=== bluevlad/Java/MAF_JDK1.5/WebContent/WEB-INF/maf-resource/table.exm_rst.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE maf-command PUBLIC
         "-//Miranet//DTD maf-command config XML V1.0//EN"
         "resourceBundle.dtd">
<bundle defaultLocale="en">
	<resource key="exmid">
		<message locale="ko" value="시험차수코드" />
		<message locale="en" value="ID" />
	</resource>
	<resource key="usn">
		<message locale="ko" value="응시자 usn" />
		<message locale="en" value="Userid" />
	</resource>
	<resource key="rstfinal">
		<message locale="ko" value="응시여부" />
		<message locale="en" value="is Applied" />
	</resource>
	<resource key="rstcont">
		<message locale="ko" value="응시횟수[재응시를 할 경우 1씩 증가]" />
		<message locale="en" value="Applied Count" />
	</resource>
	<resource key="rst_sdt">
		<message locale="ko" value="응시시작시각" />
		<message locale="en" value="Start Date" />
	</resource>
	<resource key="rst_edt">
		<message locale="ko" value="응시종료시각" />
		<message locale="en" value="End Date" />
	</resource>
	<resource key="rstatscore">
		<message locale="ko" value="객관식점수[선택형, 단답형 채점 점수]" />
		<message locale="en" value="객관식점수[선택형, 단답형 채점 점수]" />
	</resource>
	<resource key="rstatid">
		<message locale="ko" value="객관식채점id" />
		<message locale="en" value="객관식채점id" />
	</resource>
	<resource key="rstat_dt">
		<message locale="ko" value="객관식채점등록일" />
		<message locale="en" value="객관식채점등록일" />
	</resource>
	<resource key="rstmtscore">
		<message locale="ko" value="논술형 채점" />
		<message locale="en" value="논술형 채점" />
	</resource>
	<resource key="rstmtid">
		<message locale="ko" value="논술형 채점id" />
		<message locale="en" value="논술형 채점id" />
	</resource>
	<resource key="rstmt_dt">
		<message locale="ko" value="논술형 채점등록일" />
		<message locale="en" value="논술형 채점등록일" />
	</resource>
	<resource key="rstoffscore">
		<message locale="ko" value="오프라인점수[오프라인점수를 등록하거나  강사 가점(+) 처리 할 수도 있다]" />
		<message locale="en" value="오프라인점수[오프라인점수를 등록하거나  강사 가점(+) 처리 할 수도 있다]" />
	</resource>
	<resource key="rstoffid">
		<message locale="ko" value="오프라인채점id" />
		<message locale="en" value="오프라인채점id" />
	</resource>
	<resource key="rstoff_dt">
		<message locale="ko" value="오프라인채점등록일" />
		<message locale="en" value="오프라인채점등록일" />
	</resource>
	<resource key="rstflag">
		<message locale="ko" value="시험채점여부[y : 채점, n : 미채점]" />
		<message locale="en" value="is Marked" />
	</resource>
	<resource key="insert_id">
		<message locale="ko" value="최초등록자id" />
		<message locale="en" value="Writer" />
	</resource>
	<resource key="insert_dt">
		<message locale="ko" value="최초등록일" />
		<message locale="en" value="Create Date" />
	</resource>
	<resource key="update_dt">
		<message locale="ko" value="최종수정일" />
		<message locale="en" value="Update Date" />
	</resource>
	<resource key="update_id">
		<message locale="ko" value="최종수정id" />
		<message locale="en" value="Update ID" />
	</resource>

	<resource key="lang">
		<message locale="ko" value="사용언어" />
		<message locale="en" value="Language" />
	</resource>
	<resource key="rst_status">
		<message locale="ko" value="시험 진행 상태" />
		<message locale="en" value="Status" />
	</resource>
	<resource key="correct_yn">
		<message locale="ko" value="O/X" />
		<message locale="en" value="O/X" />
	</resource>
	<resource key="passing_yn">
		<message locale="ko" value="헙격여부" />
		<message locale="en" value="Success or Failure" />
	</resource>
	<resource key="usransw">
		<message locale="ko" value="Answer" />
		<message locale="en" value="Answer" />
	</resource>
	<resource key="usrscore">
		<message locale="ko" value="획득점수" />
		<message locale="en" value="Score" />
	</resource>
</bundle>
